import 'package:latlong2/latlong.dart';

class GeoPoint {
  final double lat;
  final double lng;
  final String? name;
  final bool isFuelStop;
  final RefuelStop? refuelStop;

  const GeoPoint({
    required this.lat,
    required this.lng,
    this.name,
    this.isFuelStop = false,
    this.refuelStop,
  });

  factory GeoPoint.fromJson(Map<String, dynamic> json) =>
      GeoPoint(
        lat: (json['lat'] as num).toDouble(),
        lng: (json['lng'] as num).toDouble(),
        name: json['name'] as String?,
        isFuelStop: (json['isFuelStop'] as bool?) ?? false,
        refuelStop: json['refuelStop'] != null
            ? RefuelStop.fromJson(json['refuelStop'] as Map<String, dynamic>)
            : null,
      );

  LatLng toLatLng() => LatLng(lat, lng);

  Map<String, dynamic> toJson() => {
        'lat': lat,
        'lng': lng,
        if (name != null) 'name': name,
        'isFuelStop': isFuelStop,
      };
}

class Vehicle {
  final String type; // car | suv | motorcycle | bus | rv | truck2axle | truck3axle
  final double efficiencyKmPerLiter;
  final double tankCapacityLiters;
  final double currentFuelLiters;
  final String fuelType; // petrol | diesel | cng | ev
  final bool isCustomEfficiency;

  const Vehicle({
    required this.type,
    required this.efficiencyKmPerLiter,
    required this.tankCapacityLiters,
    required this.currentFuelLiters,
    this.fuelType = 'petrol',
    this.isCustomEfficiency = false,
  });

  Map<String, dynamic> toJson() => {
        'type': type,
        'efficiencyKmPerLiter': efficiencyKmPerLiter,
        'tankCapacityLiters': tankCapacityLiters,
        'currentFuelLiters': currentFuelLiters,
        'fuelType': fuelType,
        'isCustomEfficiency': isCustomEfficiency,
      };

  factory Vehicle.fromJson(Map<String, dynamic> json) => Vehicle(
        type: json['type'] as String? ?? 'car',
        efficiencyKmPerLiter:
            (json['efficiencyKmPerLiter'] as num?)?.toDouble() ?? 15.0,
        tankCapacityLiters:
            (json['tankCapacityLiters'] as num?)?.toDouble() ?? 45.0,
        currentFuelLiters:
            (json['currentFuelLiters'] as num?)?.toDouble() ?? 45.0,
        fuelType: json['fuelType'] as String? ?? 'petrol',
        isCustomEfficiency: json['isCustomEfficiency'] as bool? ?? false,
      );

  Vehicle copyWith({
    String? type,
    double? efficiencyKmPerLiter,
    double? tankCapacityLiters,
    double? currentFuelLiters,
    String? fuelType,
    bool? isCustomEfficiency,
  }) {
    return Vehicle(
      type: type ?? this.type,
      efficiencyKmPerLiter: efficiencyKmPerLiter ?? this.efficiencyKmPerLiter,
      tankCapacityLiters: tankCapacityLiters ?? this.tankCapacityLiters,
      currentFuelLiters: currentFuelLiters ?? this.currentFuelLiters,
      fuelType: fuelType ?? this.fuelType,
      isCustomEfficiency: isCustomEfficiency ?? this.isCustomEfficiency,
    );
  }
}

class RefuelStop {
  final double lat;
  final double lng;
  final double distanceFromStartKm;

  /// Name of the real fuel station this stop snaps to.
  final String name;

  /// Station id when snapped to a real pump.
  final dynamic stationId;

  /// How far this station sits off the driving route, in km.
  final double? offRouteKm;

  /// Estimated fuel left in the tank when arriving at this station, in litres.
  final double? fuelOnArrivalLiters;

  /// Refill amount needed to top up to full capacity (litres).
  final double? refillLiters;

  /// Estimated cost for this top up refill.
  final double? estimatedCost;

  /// Unit price per litre/kWh at this location.
  final double? pricePerUnit;

  /// Currency code (e.g. INR)
  final String currency;

  /// Currency symbol (e.g. ₹)
  final String currencySymbol;

  /// Fuel type (petrol, diesel, cng, ev)
  final String fuelType;

  /// Full driving range available after refuelling (km).
  final double? remainingRangeAfterRefuelKm;

  /// Whether this stop was automatically generated by VoyPlan's smart fuel engine.
  final bool isSystemGenerated;

  /// Trip leg index where this refuel occurs (0 = first leg before Stop 1, etc.)
  final int legIndex;

  const RefuelStop({
    required this.lat,
    required this.lng,
    required this.distanceFromStartKm,
    this.name = '',
    this.stationId,
    this.offRouteKm,
    this.fuelOnArrivalLiters,
    this.refillLiters,
    this.estimatedCost,
    this.pricePerUnit,
    this.currency = 'INR',
    this.currencySymbol = '₹',
    this.fuelType = 'petrol',
    this.remainingRangeAfterRefuelKm,
    this.isSystemGenerated = true,
    this.legIndex = 0,
  });

  /// True when this stop is a real, named fuel station rather than a geometric marker.
  bool get isRealStation => name.isNotEmpty;

  factory RefuelStop.fromJson(Map<String, dynamic> json) => RefuelStop(
        lat: ((json['lat'] ?? json['latitude']) as num?)?.toDouble() ?? 0.0,
        lng: ((json['lng'] ?? json['longitude']) as num?)?.toDouble() ?? 0.0,
        distanceFromStartKm: (json['distanceFromStartKm'] as num?)?.toDouble() ?? 0.0,
        name: (json['name'] as String?) ?? '',
        stationId: json['stationId'] ?? json['id'],
        offRouteKm: ((json['offRouteKm'] ?? json['distanceFromRoute']) as num?)?.toDouble(),
        fuelOnArrivalLiters: (json['fuelOnArrivalLiters'] as num?)?.toDouble(),
        refillLiters: (json['refillLiters'] as num?)?.toDouble(),
        estimatedCost: (json['estimatedCost'] as num?)?.toDouble(),
        pricePerUnit: (json['pricePerUnit'] as num?)?.toDouble(),
        currency: (json['currency'] as String?) ?? 'INR',
        currencySymbol: (json['currencySymbol'] as String?) ?? '₹',
        fuelType: (json['fuelType'] as String?) ?? 'petrol',
        remainingRangeAfterRefuelKm: (json['remainingRangeAfterRefuelKm'] as num?)?.toDouble(),
        isSystemGenerated: (json['isSystemGenerated'] as bool?) ?? true,
        legIndex: (json['legIndex'] as num?)?.toInt() ?? 0,
      );

  String get id => stationId?.toString() ?? 'fuel_${lat.toStringAsFixed(4)}_${lng.toStringAsFixed(4)}';
  String get type => 'fuel_stop';
  double get latitude => lat;
  double get longitude => lng;
  double get distanceFromRoute => offRouteKm ?? 0.0;
  double get estimatedFuelRequired => refillLiters ?? 0.0;

  GeoPoint toGeoPoint() => GeoPoint(
        lat: lat,
        lng: lng,
        name: name.isNotEmpty ? name : 'Fuel Station',
        isFuelStop: true,
        refuelStop: this,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'type': type,
        'name': name,
        'lat': lat,
        'lng': lng,
        'latitude': latitude,
        'longitude': longitude,
        'stationId': stationId,
        'distanceFromStartKm': distanceFromStartKm,
        'distanceFromRoute': distanceFromRoute,
        'offRouteKm': offRouteKm,
        'fuelOnArrivalLiters': fuelOnArrivalLiters,
        'refillLiters': refillLiters,
        'estimatedFuelRequired': estimatedFuelRequired,
        'estimatedCost': estimatedCost,
        'pricePerUnit': pricePerUnit,
        'currency': currency,
        'currencySymbol': currencySymbol,
        'fuelType': fuelType,
        'remainingRangeAfterRefuelKm': remainingRangeAfterRefuelKm,
        'isSystemGenerated': isSystemGenerated,
        'legIndex': legIndex,
      };

  LatLng toLatLng() => LatLng(lat, lng);
}

/// A hiking/trekking trail surfaced by the AllTrails-style discovery feature.
class Trek {
  final String id;
  final String name;
  final double lat;
  final double lng;
  final double distanceFromSearchKm;
  final double? lengthKm;
  final String? difficulty;
  final String type;
  final String? description;
  final String? imageUrl;

  /// Ordered trail geometry (may be empty when OSM has no line for it).
  final List<LatLng> path;

  const Trek({
    required this.id,
    required this.name,
    required this.lat,
    required this.lng,
    required this.distanceFromSearchKm,
    this.lengthKm,
    this.difficulty,
    this.type = 'trail',
    this.description,
    this.imageUrl,
    this.path = const [],
  });

  bool get hasPath => path.length > 1;

  LatLng toLatLng() => LatLng(lat, lng);
  GeoPoint toGeoPoint() => GeoPoint(lat: lat, lng: lng, name: name);

  factory Trek.fromJson(Map<String, dynamic> json) => Trek(
        id: json['id'] as String,
        name: json['name'] as String,
        lat: (json['lat'] as num).toDouble(),
        lng: (json['lng'] as num).toDouble(),
        distanceFromSearchKm: (json['distanceFromSearchKm'] as num?)?.toDouble() ?? 0,
        lengthKm: (json['lengthKm'] as num?)?.toDouble(),
        difficulty: json['difficulty'] as String?,
        type: (json['type'] as String?) ?? 'trail',
        description: json['description'] as String?,
        imageUrl: json['imageUrl'] as String?,
        path: (json['path'] as List? ?? [])
            .map((e) => LatLng(
                  ((e as Map)['lat'] as num).toDouble(),
                  (e['lng'] as num).toDouble(),
                ))
            .toList(),
      );
}

/// One time block in the smart AI itinerary timeline.
class TimelineBlock {
  final String id;
  String start;
  String end;
  final String type; // start|activity|travel|meal|coffee|rest|checkin|checkout|buffer|shopping|freetime|return|fuel
  String title;
  final String place;
  final double? lat;
  final double? lng;
  final String address;
  final String city;
  final String state;
  final String country;
  int durationMin;
  final int travelMin;
  final double distanceKm;
  final String breakType; // breakfast|lunch|dinner|tea (for meal/break blocks)
  final String reason;
  final String travelMode; // drive|flight|train|bus|ferry|walk (travel/return legs)
  final List<String> categories; // matched place categories
  final String whyIncluded; // explanation for why this stop was chosen
  final String openingHours;
  final int day;
  final int sequence;
  final bool isFuelStop;
  bool isConfirmed;
  final String placeId;
  int stayDuration;

  TimelineBlock({
    this.id = '',
    required this.start,
    required this.end,
    required this.type,
    required this.title,
    this.place = '',
    this.lat,
    this.lng,
    this.address = '',
    this.city = '',
    this.state = '',
    this.country = 'India',
    this.durationMin = 0,
    this.travelMin = 0,
    this.distanceKm = 0,
    this.breakType = '',
    this.reason = '',
    this.travelMode = '',
    this.categories = const [],
    this.whyIncluded = '',
    this.openingHours = '',
    this.day = 1,
    this.sequence = 0,
    this.isFuelStop = false,
    this.isConfirmed = false,
    this.placeId = '',
    int? stayDuration,
  }) : stayDuration = stayDuration ?? durationMin;

  factory TimelineBlock.fromJson(Map<String, dynamic> j) {
    final dMin = (j['durationMin'] as num?)?.toInt() ?? 0;
    return TimelineBlock(
        id: (j['id'] ?? '').toString(),
        start: (j['start'] ?? '').toString(),
        end: (j['end'] ?? '').toString(),
        type: (j['type'] ?? 'activity').toString(),
        title: (j['title'] ?? '').toString(),
        place: (j['place'] ?? '').toString(),
        lat: (j['lat'] as num?)?.toDouble() ?? (j['latitude'] as num?)?.toDouble(),
        lng: (j['lng'] as num?)?.toDouble() ?? (j['longitude'] as num?)?.toDouble(),
        address: (j['address'] ?? '').toString(),
        city: (j['city'] ?? '').toString(),
        state: (j['state'] ?? '').toString(),
        country: (j['country'] ?? 'India').toString(),
        durationMin: dMin,
        travelMin: (j['travelMin'] as num?)?.toInt() ?? 0,
        distanceKm: (j['distanceKm'] as num?)?.toDouble() ?? 0,
        breakType: (j['breakType'] ?? '').toString(),
        reason: (j['reason'] ?? '').toString(),
        travelMode: (j['travelMode'] ?? '').toString(),
        categories: (j['categories'] as List? ?? [])
            .map((e) => e.toString())
            .where((s) => s.isNotEmpty)
            .toList(),
        whyIncluded: (j['whyIncluded'] ?? '').toString(),
        openingHours: (j['openingHours'] ?? '').toString(),
        day: (j['day'] as num?)?.toInt() ?? 1,
        sequence: (j['sequence'] as num?)?.toInt() ?? 0,
        isFuelStop: j['isFuelStop'] == true || j['type'] == 'fuel',
        isConfirmed: j['isConfirmed'] == true,
        placeId: (j['placeId'] ?? '').toString(),
        stayDuration: (j['stayDuration'] as num?)?.toInt() ?? dMin,
      );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'start': start,
        'end': end,
        'type': type,
        'title': title,
        'place': place,
        'lat': lat,
        'lng': lng,
        'address': address,
        'city': city,
        'state': state,
        'country': country,
        'durationMin': durationMin,
        'travelMin': travelMin,
        'distanceKm': distanceKm,
        'breakType': breakType,
        'reason': reason,
        'travelMode': travelMode,
        'categories': categories,
        'whyIncluded': whyIncluded,
        'openingHours': openingHours,
        'day': day,
        'sequence': sequence,
        'isFuelStop': isFuelStop,
        'isConfirmed': isConfirmed,
        'placeId': placeId,
        'stayDuration': stayDuration,
      };
}

class PlaceCategoryOption {
  final String id;
  final String label;
  final String icon;
  final String description;

  const PlaceCategoryOption({
    required this.id,
    required this.label,
    required this.icon,
    this.description = '',
  });
}

const List<PlaceCategoryOption> kPlaceCategories = [
  PlaceCategoryOption(id: 'temples', label: 'Temples & Religious Places', icon: '🛕', description: 'Sacred shrines, heritage temples & spiritual places'),
  PlaceCategoryOption(id: 'waterfalls_rivers', label: 'Rivers, Lakes & Waterfalls', icon: '🌊', description: 'Scenic falls, rivers, boating lakes & watersides'),
  PlaceCategoryOption(id: 'viewpoints', label: 'Viewpoints & Scenic Places', icon: '🌄', description: 'Panoramic vistas, valleys & sunrise/sunset spots'),
  PlaceCategoryOption(id: 'hills_mountains', label: 'Hills & Mountains', icon: '⛰️', description: 'Hill stations, mountain peaks & cool altitudes'),
  PlaceCategoryOption(id: 'historical_heritage', label: 'Historical & Heritage Places', icon: '🏛️', description: 'Ancient ruins, UNESCO sites & archaeological wonders'),
  PlaceCategoryOption(id: 'famous_places', label: 'Famous / Must-Visit Places', icon: '⭐', description: 'Top-rated bucket list landmarks & signature spots'),
  PlaceCategoryOption(id: 'forts_palaces', label: 'Forts & Palaces', icon: '🏰', description: 'Royal residences, hill forts & grand architecture'),
  PlaceCategoryOption(id: 'nature_forests', label: 'Nature & Forests', icon: '🌳', description: 'Botanical gardens, lush plantations & green trails'),
  PlaceCategoryOption(id: 'beaches', label: 'Beaches', icon: '🏖️', description: 'Golden sands, coastal shores & ocean viewpoints'),
  PlaceCategoryOption(id: 'wildlife_national_parks', label: 'Wildlife & National Parks', icon: '🐘', description: 'Animal sanctuaries, safari parks & reserves'),
  PlaceCategoryOption(id: 'monuments_landmarks', label: 'Monuments & Landmarks', icon: '🗿', description: 'Iconic statues, memorials & architectural pillars'),
  PlaceCategoryOption(id: 'city_attractions', label: 'Famous City Attractions', icon: '🏙️', description: 'Urban sights, city plazas & modern landmarks'),
  PlaceCategoryOption(id: 'bridges_dams', label: 'Famous Bridges / Dams', icon: '🌉', description: 'Mega reservoirs, scenic dams & historic bridges'),
  PlaceCategoryOption(id: 'markets_local', label: 'Famous Markets & Local Places', icon: '🛍️', description: 'Traditional bazaars, local craft streets & food lanes'),
  PlaceCategoryOption(id: 'cultural_places', label: 'Cultural Places', icon: '🎨', description: 'Art galleries, folk villages & cultural centers'),
  PlaceCategoryOption(id: 'photography_spots', label: 'Instagrammable / Photography Spots', icon: '📸', description: 'Aesthetic photo locations & picturesque backdrops'),
];

/// One day of the smart AI itinerary timeline.
class SmartDay {
  final int day;
  final String date;
  final String title;
  final List<TimelineBlock> blocks;

  SmartDay({required this.day, this.date = '', this.title = '', required this.blocks});

  factory SmartDay.fromJson(Map<String, dynamic> j) => SmartDay(
        day: (j['day'] as num?)?.toInt() ?? 1,
        date: (j['date'] ?? '').toString(),
        title: (j['title'] ?? '').toString(),
        blocks: (j['blocks'] as List? ?? [])
            .map((e) => TimelineBlock.fromJson((e as Map).cast<String, dynamic>()))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'day': day,
        'date': date,
        'title': title,
        'blocks': blocks.map((b) => b.toJson()).toList(),
      };
}


class FuelPlan {
  final bool needsRefuel;
  final double totalDistanceKm;
  final List<RefuelStop> refuelStops;

  /// True when part of the route has no reachable fuel station within
  /// the vehicle's safe driving range — signals a critical warning.
  final bool unreachable;

  /// Safe planning range with reserve (km).
  final double? safeRangeKm;

  /// Human-readable explanation if unreachable.
  final String? unreachableReason;

  /// Total estimated cost for all planned refuels along the trip.
  final double? totalRefuelCost;

  /// Total liters/units to be refilled across all stops.
  final double? totalRefillLiters;

  const FuelPlan({
    required this.needsRefuel,
    required this.totalDistanceKm,
    required this.refuelStops,
    this.unreachable = false,
    this.safeRangeKm,
    this.unreachableReason,
    this.totalRefuelCost,
    this.totalRefillLiters,
  });

  factory FuelPlan.fromJson(Map<String, dynamic> json) => FuelPlan(
        needsRefuel: json['needsRefuel'] as bool? ?? false,
        totalDistanceKm: (json['totalDistanceKm'] as num?)?.toDouble() ?? 0.0,
        unreachable: (json['unreachable'] as bool?) ?? false,
        safeRangeKm: (json['safeRangeKm'] as num?)?.toDouble(),
        unreachableReason: json['unreachableReason'] as String?,
        totalRefuelCost: (json['totalRefuelCost'] as num?)?.toDouble(),
        totalRefillLiters: (json['totalRefillLiters'] as num?)?.toDouble(),
        refuelStops: ((json['refuelStops'] as List?) ?? [])
            .map((e) => RefuelStop.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

class FuelPrice {
  final String country;
  final String countryCode;
  final String state;
  final String city;
  final String fuelType;
  final double price;
  final String currency;
  final String currencySymbol;
  final String unit;
  final String effectiveAt;
  final String lastUpdated;
  final String source;
  final String status; // 'live' | 'cached' | 'estimated' | 'unavailable'
  final String confidence; // 'high' | 'medium' | 'low'
  final Map<String, double> allPrices;

  const FuelPrice({
    required this.country,
    this.countryCode = 'IN',
    required this.state,
    required this.city,
    required this.fuelType,
    required this.price,
    this.currency = 'INR',
    this.currencySymbol = '₹',
    this.unit = 'litre',
    required this.effectiveAt,
    required this.lastUpdated,
    this.source = 'PPAC / Official OMC Daily RSP',
    this.status = 'live',
    this.confidence = 'high',
    this.allPrices = const {},
  });

  factory FuelPrice.fromJson(Map<String, dynamic> json) {
    final pricesMap = <String, double>{};
    if (json['allPrices'] is Map) {
      (json['allPrices'] as Map).forEach((k, v) {
        if (v is num) pricesMap[k.toString()] = v.toDouble();
      });
    }

    return FuelPrice(
      country: json['country'] as String? ?? 'India',
      countryCode: json['countryCode'] as String? ?? 'IN',
      state: json['state'] as String? ?? 'Karnataka',
      city: json['city'] as String? ?? 'Bengaluru',
      fuelType: json['fuelType'] as String? ?? 'petrol',
      price: (json['price'] as num?)?.toDouble() ?? 102.86,
      currency: json['currency'] as String? ?? 'INR',
      currencySymbol: json['currencySymbol'] as String? ?? '₹',
      unit: json['unit'] as String? ?? 'litre',
      effectiveAt: json['effectiveAt'] as String? ?? DateTime.now().toIso8601String(),
      lastUpdated: json['lastUpdated'] as String? ?? DateTime.now().toIso8601String(),
      source: json['source'] as String? ?? 'Official OMC Daily RSP',
      status: json['status'] as String? ?? 'live',
      confidence: json['confidence'] as String? ?? 'high',
      allPrices: pricesMap,
    );
  }

  Map<String, dynamic> toJson() => {
        'country': country,
        'countryCode': countryCode,
        'state': state,
        'city': city,
        'fuelType': fuelType,
        'price': price,
        'currency': currency,
        'currencySymbol': currencySymbol,
        'unit': unit,
        'effectiveAt': effectiveAt,
        'lastUpdated': lastUpdated,
        'source': source,
        'status': status,
        'confidence': confidence,
        'allPrices': allPrices,
      };

  bool get isRealTime => status == 'live';
  String get provider => source;
}

class FuelEstimate {
  final double distanceKm;
  final double vehicleEfficiency;
  final String fuelType;
  final double fuelRequired;
  final double pricePerUnit;
  final String currency;
  final String currencySymbol;
  final String unit;
  final double totalCost;
  final String startRegion;
  final String endRegion;
  final bool isMultiState;
  final bool isDefaultMileage;
  final String source;
  final String effectiveAt;
  final String lastUpdated;
  final double currentFuelLiters;
  final double additionalFuelRequiredLiters;
  final double estimatedCost;
  final String applicableLocation;
  final String updatedAtText;
  final String status;

  const FuelEstimate({
    required this.distanceKm,
    required this.vehicleEfficiency,
    required this.fuelType,
    required this.fuelRequired,
    required this.pricePerUnit,
    this.currentFuelLiters = 0.0,
    this.additionalFuelRequiredLiters = 0.0,
    this.estimatedCost = 0.0,
    this.currency = 'INR',
    this.currencySymbol = '₹',
    this.unit = 'litre',
    required this.totalCost,
    this.startRegion = '',
    this.endRegion = '',
    this.applicableLocation = '',
    this.isMultiState = false,
    this.isDefaultMileage = false,
    this.source = 'CarDekho / OMC Daily Retail Price',
    this.updatedAtText = 'Updated: Today',
    required this.effectiveAt,
    required this.lastUpdated,
    this.status = 'live',
  });

  double get totalFuelCost => totalCost;
  double get fuelRequiredLiters => fuelRequired;
  double get appliedPricePerLiter => pricePerUnit;
  double get estimatedFuelCost => estimatedCost > 0 ? estimatedCost : totalCost;
  bool get isPriceAvailable => status.toLowerCase() != 'unavailable' && pricePerUnit > 0;

  String get formattedFuelRequired => '${fuelRequired.toStringAsFixed(1)} L';
  String get formattedCurrentFuel => '${currentFuelLiters.toStringAsFixed(1)} L';
  String get formattedAdditionalRequired => '${additionalFuelRequiredLiters.toStringAsFixed(1)} L';
  String get formattedFuelPrice => isPriceAvailable
      ? '$currencySymbol${pricePerUnit.toStringAsFixed(2)}/${unit == "litre" ? "L" : unit}'
      : 'Fuel price unavailable';
  String get formattedEstimatedCost => '$currencySymbol${(estimatedCost > 0 ? estimatedCost : totalCost).toStringAsFixed(2)}';

  String get regionName => applicableLocation.isNotEmpty
      ? applicableLocation
      : (startRegion.isNotEmpty
          ? (endRegion.isNotEmpty && isMultiState ? '$startRegion ➔ $endRegion' : startRegion)
          : 'India');
  String get priceWithLocation => '$formattedFuelPrice ($regionName)';
  bool get isMultiRegionEstimate => isMultiState;
  String get dataSource => source;

  factory FuelEstimate.fromJson(Map<String, dynamic> json) {
    final req = (json['fuelRequired'] as num?)?.toDouble() ??
        (json['fuelRequiredLiters'] as num?)?.toDouble() ?? 0.0;
    final cur = (json['currentFuelLiters'] as num?)?.toDouble() ?? 0.0;
    final add = (json['additionalFuelRequiredLiters'] as num?)?.toDouble() ??
        ((req - cur) > 0 ? req - cur : 0.0);
    final tot = (json['totalCost'] as num?)?.toDouble() ??
        (json['totalFuelCost'] as num?)?.toDouble() ?? 0.0;
    final est = (json['estimatedCost'] as num?)?.toDouble() ?? tot;

    return FuelEstimate(
      distanceKm: (json['distanceKm'] as num?)?.toDouble() ?? 0.0,
      vehicleEfficiency: (json['vehicleEfficiency'] as num?)?.toDouble() ?? 15.0,
      fuelType: json['fuelType'] as String? ?? 'petrol',
      fuelRequired: req,
      currentFuelLiters: cur,
      additionalFuelRequiredLiters: add,
      estimatedCost: est,
      pricePerUnit: (json['pricePerUnit'] as num?)?.toDouble() ?? 102.45,
      currency: json['currency'] as String? ?? 'INR',
      currencySymbol: json['currencySymbol'] as String? ?? '₹',
      unit: json['unit'] as String? ?? 'litre',
      totalCost: tot,
      startRegion: json['startRegion'] as String? ?? '',
      endRegion: json['endRegion'] as String? ?? '',
      applicableLocation: json['applicableLocation'] as String? ??
          (json['startRegion'] as String? ?? ''),
      isMultiState: json['isMultiState'] as bool? ?? false,
      isDefaultMileage: json['isDefaultMileage'] as bool? ?? false,
      source: json['source'] as String? ?? 'CarDekho / OMC Daily Retail Price',
      updatedAtText: json['updatedAtText'] as String? ?? 'Updated: Today',
      effectiveAt: json['effectiveAt'] as String? ?? DateTime.now().toIso8601String(),
      lastUpdated: json['lastUpdated'] as String? ?? DateTime.now().toIso8601String(),
      status: json['status'] as String? ?? 'live',
    );
  }

  Map<String, dynamic> toJson() => {
        'distanceKm': distanceKm,
        'vehicleEfficiency': vehicleEfficiency,
        'fuelType': fuelType,
        'fuelRequired': fuelRequired,
        'currentFuelLiters': currentFuelLiters,
        'additionalFuelRequiredLiters': additionalFuelRequiredLiters,
        'estimatedCost': estimatedCost,
        'pricePerUnit': pricePerUnit,
        'currency': currency,
        'currencySymbol': currencySymbol,
        'unit': unit,
        'totalCost': totalCost,
        'totalFuelCost': totalCost,
        'startRegion': startRegion,
        'endRegion': endRegion,
        'applicableLocation': applicableLocation,
        'isMultiState': isMultiState,
        'isDefaultMileage': isDefaultMileage,
        'source': source,
        'updatedAtText': updatedAtText,
        'effectiveAt': effectiveAt,
        'lastUpdated': lastUpdated,
        'status': status,
      };
}

class TollPlaza {
  final String id;
  final String name;
  final String highway;
  final double latitude;
  final double longitude;
  final double amount;
  final double cashAmount;
  final String vehicleClass;
  final String direction;
  final double distanceAlongRouteKm;
  final int routeIndex;
  final bool isEstimated;
  final String dataSource;

  const TollPlaza({
    required this.id,
    required this.name,
    required this.highway,
    required this.latitude,
    required this.longitude,
    required this.amount,
    required this.cashAmount,
    required this.vehicleClass,
    this.direction = 'single',
    required this.distanceAlongRouteKm,
    this.routeIndex = 0,
    this.isEstimated = false,
    this.dataSource = 'NHAI Toll Information System (TIS)',
  });

  factory TollPlaza.fromJson(Map<String, dynamic> json) => TollPlaza(
        id: json['id'] as String? ?? '',
        name: json['name'] as String? ?? 'Toll Plaza',
        highway: json['highway'] as String? ?? 'Highway',
        latitude: (json['latitude'] as num?)?.toDouble() ?? 0.0,
        longitude: (json['longitude'] as num?)?.toDouble() ?? 0.0,
        amount: (json['amount'] as num?)?.toDouble() ?? 0.0,
        cashAmount: (json['cashAmount'] as num?)?.toDouble() ??
            ((json['amount'] as num?)?.toDouble() ?? 0.0) * 2,
        vehicleClass: json['vehicleClass'] as String? ?? 'car',
        direction: json['direction'] as String? ?? 'single',
        distanceAlongRouteKm:
            (json['distanceAlongRouteKm'] as num?)?.toDouble() ?? 0.0,
        routeIndex: json['routeIndex'] as int? ?? 0,
        isEstimated: json['isEstimated'] as bool? ?? false,
        dataSource: json['dataSource'] as String? ?? 'NHAI TIS',
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'highway': highway,
        'latitude': latitude,
        'longitude': longitude,
        'amount': amount,
        'cashAmount': cashAmount,
        'vehicleClass': vehicleClass,
        'direction': direction,
        'distanceAlongRouteKm': distanceAlongRouteKm,
        'routeIndex': routeIndex,
        'isEstimated': isEstimated,
        'dataSource': dataSource,
      };
}

class TollEstimate {
  final bool hasTolls;
  final String currency;
  final double? minTollCost;
  final double? maxTollCost;
  final double? fastagTollCost;
  final double? cashTollCost;
  final double? fuelCost;
  final double? totalAmount;
  final int tollCount;
  final List<TollPlaza> tolls;
  final String? vehicleClass;
  final bool isEstimated;
  final String? dataSource;
  final String? lastUpdated;

  const TollEstimate({
    required this.hasTolls,
    required this.currency,
    this.minTollCost,
    this.maxTollCost,
    this.fastagTollCost,
    this.cashTollCost,
    this.fuelCost,
    this.totalAmount,
    this.tollCount = 0,
    this.tolls = const [],
    this.vehicleClass,
    this.isEstimated = false,
    this.dataSource,
    this.lastUpdated,
  });

  factory TollEstimate.fromJson(Map<String, dynamic> json) {
    final rawTolls = json['tolls'] as List<dynamic>? ?? [];
    final tollsList = rawTolls
        .map((e) => TollPlaza.fromJson(e as Map<String, dynamic>))
        .toList();
    final count = json['tollCount'] as int? ?? tollsList.length;
    final total = (json['totalAmount'] as num?)?.toDouble() ??
        (json['fastagTollCost'] as num?)?.toDouble() ??
        (tollsList.isNotEmpty
            ? tollsList.fold<double>(0.0, (sum, t) => sum + t.amount)
            : null);

    return TollEstimate(
      hasTolls: json['hasTolls'] as bool? ?? (count > 0 || (total != null && total > 0)),
      currency: json['currency'] as String? ?? 'INR',
      minTollCost: (json['minTollCost'] as num?)?.toDouble() ?? total,
      maxTollCost: (json['maxTollCost'] as num?)?.toDouble() ??
          (json['cashTollCost'] as num?)?.toDouble(),
      fastagTollCost: (json['fastagTollCost'] as num?)?.toDouble() ?? total,
      cashTollCost: (json['cashTollCost'] as num?)?.toDouble() ??
          (total != null ? total * 2 : null),
      fuelCost: (json['fuelCost'] as num?)?.toDouble(),
      totalAmount: total,
      tollCount: count,
      tolls: tollsList,
      vehicleClass: json['vehicleClass'] as String?,
      isEstimated: json['isEstimated'] as bool? ?? false,
      dataSource: json['dataSource'] as String?,
      lastUpdated: json['lastUpdated'] as String?,
    );
  }

  Map<String, dynamic> toJson() => {
        'hasTolls': hasTolls,
        'currency': currency,
        'minTollCost': minTollCost,
        'maxTollCost': maxTollCost,
        'fastagTollCost': fastagTollCost,
        'cashTollCost': cashTollCost,
        'fuelCost': fuelCost,
        'totalAmount': totalAmount,
        'tollCount': tollCount,
        'tolls': tolls.map((t) => t.toJson()).toList(),
        'vehicleClass': vehicleClass,
        'isEstimated': isEstimated,
        'dataSource': dataSource,
        'lastUpdated': lastUpdated,
      };
}

class PlaceOfInterest {
  final int id;
  final String name;
  final double lat;
  final double lng;
  final String? address;
  final double? rating;
  final int? reviewsCount;
  final String? deity;
  final String? timing;
  final String? highlights;
  final String? categoryType;

  const PlaceOfInterest({
    required this.id,
    required this.name,
    required this.lat,
    required this.lng,
    this.address,
    this.rating,
    this.reviewsCount,
    this.deity,
    this.timing,
    this.highlights,
    this.categoryType,
  });

  factory PlaceOfInterest.fromJson(Map<String, dynamic> json) => PlaceOfInterest(
        id: json['id'] as int,
        name: json['name'] as String,
        lat: (json['lat'] as num).toDouble(),
        lng: (json['lng'] as num).toDouble(),
        address: json['address'] as String?,
        rating: (json['rating'] as num?)?.toDouble(),
        reviewsCount: json['reviewsCount'] as int?,
        deity: json['deity'] as String?,
        timing: json['timing'] as String?,
        highlights: json['highlights'] as String?,
        categoryType: json['categoryType'] as String?,
      );

  LatLng toLatLng() => LatLng(lat, lng);
}

class WeatherPoint {
  final double lat;
  final double lng;
  final double distanceFromStartKm;
  final double? tempC;
  final String description;
  final String icon; // clear | partly_cloudy | cloudy | fog | drizzle | rain | snow | thunderstorm
  final int? windKph;
  final int? humidity;
  final int? rainChancePct;

  const WeatherPoint({
    required this.lat,
    required this.lng,
    required this.distanceFromStartKm,
    required this.tempC,
    required this.description,
    required this.icon,
    required this.windKph,
    required this.humidity,
    required this.rainChancePct,
  });

  factory WeatherPoint.fromJson(Map<String, dynamic> json) => WeatherPoint(
        lat: (json['lat'] as num).toDouble(),
        lng: (json['lng'] as num).toDouble(),
        distanceFromStartKm: (json['distanceFromStartKm'] as num?)?.toDouble() ?? 0,
        tempC: (json['tempC'] as num?)?.toDouble(),
        description: json['description'] as String? ?? 'Unknown',
        icon: json['icon'] as String? ?? 'cloudy',
        windKph: (json['windKph'] as num?)?.toInt(),
        humidity: (json['humidity'] as num?)?.toInt(),
        rainChancePct: (json['rainChancePct'] as num?)?.toInt(),
      );

  LatLng toLatLng() => LatLng(lat, lng);
}

class RouteWeather {
  final bool hasAlerts;
  final List<WeatherPoint> points;

  const RouteWeather({required this.hasAlerts, required this.points});

  factory RouteWeather.fromJson(Map<String, dynamic> json) => RouteWeather(
        hasAlerts: json['hasAlerts'] as bool? ?? false,
        points: (json['points'] as List? ?? [])
            .map((e) => WeatherPoint.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

class TripBudget {
  final String currency;
  final int days;
  final int nights;
  final int travellers;
  final bool international;
  final int fuel;
  final int tolls;
  final int transport; // flight/train/bus/ferry tickets
  final int localTransport; // destination taxis / local getting-around
  final int breakfast;
  final int lunch;
  final int teaSnacks;
  final int dinner;
  final int food;
  final int other;
  final int stay;
  final int buffer;
  final int total;
  final int perDay;

  const TripBudget({
    required this.currency,
    required this.days,
    required this.nights,
    required this.travellers,
    this.international = false,
    required this.fuel,
    required this.tolls,
    this.transport = 0,
    this.localTransport = 0,
    this.breakfast = 0,
    this.lunch = 0,
    this.teaSnacks = 0,
    this.dinner = 0,
    required this.food,
    this.other = 0,
    required this.stay,
    required this.buffer,
    required this.total,
    required this.perDay,
  });

  factory TripBudget.fromJson(Map<String, dynamic> json) {
    final b = (json['breakdown'] as Map<String, dynamic>? ?? {});
    final foodTotal = (b['food'] as num?)?.toInt() ?? 0;
    final bf = (b['breakfast'] as num?)?.toInt() ??
        (foodTotal > 0 ? (foodTotal * 0.25).round() : 250);
    final ln = (b['lunch'] as num?)?.toInt() ??
        (foodTotal > 0 ? (foodTotal * 0.35).round() : 500);
    final ts = (b['teaSnacks'] as num?)?.toInt() ??
        (foodTotal > 0 ? (foodTotal * 0.15).round() : 200);
    final dn = (b['dinner'] as num?)?.toInt() ??
        (foodTotal > 0 ? (foodTotal * 0.25).round() : 500);
    final calculatedFood = bf + ln + ts + dn;
    final otherVal = (b['other'] as num?)?.toInt() ?? (b['buffer'] as num?)?.toInt() ?? 300;

    return TripBudget(
      currency: json['currency'] as String? ?? 'INR',
      days: (json['days'] as num?)?.toInt() ?? 1,
      nights: (json['nights'] as num?)?.toInt() ?? 0,
      travellers: (json['travellers'] as num?)?.toInt() ?? 1,
      international: json['international'] as bool? ?? false,
      fuel: (b['fuel'] as num?)?.toInt() ?? 0,
      tolls: (b['tolls'] as num?)?.toInt() ?? 0,
      transport: (b['transport'] as num?)?.toInt() ?? 0,
      localTransport: (b['localTransport'] as num?)?.toInt() ?? 0,
      breakfast: bf,
      lunch: ln,
      teaSnacks: ts,
      dinner: dn,
      food: foodTotal > 0 ? foodTotal : calculatedFood,
      other: otherVal,
      stay: (b['stay'] as num?)?.toInt() ?? 0,
      buffer: (b['buffer'] as num?)?.toInt() ?? otherVal,
      total: (json['total'] as num?)?.toInt() ?? 0,
      perDay: (json['perDay'] as num?)?.toInt() ?? 0,
    );
  }

  Map<String, dynamic> toJson() => {
    'currency': currency,
    'days': days,
    'nights': nights,
    'travellers': travellers,
    'international': international,
    'total': total,
    'perDay': perDay,
    'breakdown': {
      'fuel': fuel,
      'tolls': tolls,
      'transport': transport,
      'localTransport': localTransport,
      'food': food,
      'stay': stay,
      'buffer': buffer,
      'other': other,
    },
  };
}

class DepartureAdvice {
  final int bestOffsetHours;
  final String bestLabel;
  final int driestRainPct;
  final int nowRainPct;
  final String recommendation;

  const DepartureAdvice({
    required this.bestOffsetHours,
    required this.bestLabel,
    required this.driestRainPct,
    required this.nowRainPct,
    required this.recommendation,
  });

  factory DepartureAdvice.fromJson(Map<String, dynamic> json) => DepartureAdvice(
        bestOffsetHours: (json['bestOffsetHours'] as num?)?.toInt() ?? 0,
        bestLabel: json['bestLabel'] as String? ?? 'now',
        driestRainPct: (json['driestRainPct'] as num?)?.toInt() ?? 0,
        nowRainPct: (json['nowRainPct'] as num?)?.toInt() ?? 0,
        recommendation: json['recommendation'] as String? ?? '',
      );

  /// True when leaving later meaningfully reduces rain risk.
  bool get suggestsWaiting => bestOffsetHours > 0 && driestRainPct < nowRainPct - 15;
}

class RestBreak {
  final double afterHours;
  final double distanceFromStartKm;
  final double lat;
  final double lng;
  final String label;

  const RestBreak({
    required this.afterHours,
    required this.distanceFromStartKm,
    required this.lat,
    required this.lng,
    required this.label,
  });

  factory RestBreak.fromJson(Map<String, dynamic> json) => RestBreak(
        afterHours: (json['afterHours'] as num?)?.toDouble() ?? 0,
        distanceFromStartKm: (json['distanceFromStartKm'] as num?)?.toDouble() ?? 0,
        lat: (json['lat'] as num?)?.toDouble() ?? 0,
        lng: (json['lng'] as num?)?.toDouble() ?? 0,
        label: json['label'] as String? ?? 'Rest break',
      );

  LatLng toLatLng() => LatLng(lat, lng);
}

class DayPlan {
  final int day;
  final double fromKm;
  final double toKm;
  final double distanceKm;
  final double driveHours;
  final double endLat;
  final double endLng;
  final bool isFinal;

  const DayPlan({
    required this.day,
    required this.fromKm,
    required this.toKm,
    required this.distanceKm,
    required this.driveHours,
    required this.endLat,
    required this.endLng,
    required this.isFinal,
  });

  factory DayPlan.fromJson(Map<String, dynamic> json) => DayPlan(
        day: (json['day'] as num?)?.toInt() ?? 1,
        fromKm: (json['fromKm'] as num?)?.toDouble() ?? 0,
        toKm: (json['toKm'] as num?)?.toDouble() ?? 0,
        distanceKm: (json['distanceKm'] as num?)?.toDouble() ?? 0,
        driveHours: (json['driveHours'] as num?)?.toDouble() ?? 0,
        endLat: (json['endLat'] as num?)?.toDouble() ?? 0,
        endLng: (json['endLng'] as num?)?.toDouble() ?? 0,
        isFinal: json['isFinal'] as bool? ?? false,
      );
}

class WikiAttraction {
  final int pageid;
  final String title;
  final double lat;
  final double lng;
  final int distanceMeters;
  final String summary;
  final String? thumbnailUrl;
  final String pageUrl;

  const WikiAttraction({
    required this.pageid,
    required this.title,
    required this.lat,
    required this.lng,
    required this.distanceMeters,
    required this.summary,
    this.thumbnailUrl,
    required this.pageUrl,
  });

  factory WikiAttraction.fromJson(Map<String, dynamic> json) => WikiAttraction(
        pageid: (json['pageid'] as num?)?.toInt() ?? 0,
        title: json['title'] as String? ?? 'Attraction',
        lat: (json['lat'] as num?)?.toDouble() ?? 0.0,
        lng: (json['lng'] as num?)?.toDouble() ?? 0.0,
        distanceMeters: (json['distanceMeters'] as num?)?.toInt() ?? 0,
        summary: json['summary'] as String? ?? '',
        thumbnailUrl: json['thumbnailUrl'] as String?,
        pageUrl: json['pageUrl'] as String? ?? '',
      );
}

class DestinationEvent {
  final String id;
  final String title;
  final String category;
  final String location;
  final String date;
  final String description;
  final String? url;

  const DestinationEvent({
    required this.id,
    required this.title,
    required this.category,
    required this.location,
    required this.date,
    required this.description,
    this.url,
  });

  factory DestinationEvent.fromJson(Map<String, dynamic> json) => DestinationEvent(
        id: json['id'] as String? ?? '',
        title: json['title'] as String? ?? 'Local Event',
        category: json['category'] as String? ?? 'General',
        location: json['location'] as String? ?? '',
        date: json['date'] as String? ?? 'Upcoming',
        description: json['description'] as String? ?? '',
        url: json['url'] as String?,
      );
}

class CanonicalRouteStep {
  final String instruction;
  final int distanceMeters;
  final int durationSeconds;
  final String roadName;
  final String maneuverType;
  final String modifier;
  final GeoPoint? location;

  const CanonicalRouteStep({
    required this.instruction,
    this.distanceMeters = 0,
    this.durationSeconds = 0,
    this.roadName = '',
    this.maneuverType = 'straight',
    this.modifier = '',
    this.location,
  });

  factory CanonicalRouteStep.fromJson(Map<String, dynamic> json) {
    return CanonicalRouteStep(
      instruction: json['instruction'] as String? ?? 'Follow the road',
      distanceMeters: (json['distanceMeters'] as num?)?.toInt() ?? 0,
      durationSeconds: (json['durationSeconds'] as num?)?.toInt() ?? 0,
      roadName: json['roadName'] as String? ?? '',
      maneuverType: json['maneuverType'] as String? ?? 'straight',
      modifier: json['modifier'] as String? ?? '',
      location: json['location'] != null
          ? GeoPoint.fromJson((json['location'] as Map).cast<String, dynamic>())
          : null,
    );
  }

  Map<String, dynamic> toJson() => {
    'instruction': instruction,
    'distanceMeters': distanceMeters,
    'durationSeconds': durationSeconds,
    'roadName': roadName,
    'maneuverType': maneuverType,
    'modifier': modifier,
    if (location != null) 'location': location!.toJson(),
  };
}

class CanonicalRouteLeg {
  final int legIndex;
  final int distanceMeters;
  final int durationSeconds;
  final List<CanonicalRouteStep> steps;

  const CanonicalRouteLeg({
    required this.legIndex,
    this.distanceMeters = 0,
    this.durationSeconds = 0,
    this.steps = const [],
  });

  factory CanonicalRouteLeg.fromJson(Map<String, dynamic> json) {
    return CanonicalRouteLeg(
      legIndex: (json['legIndex'] as num?)?.toInt() ?? 0,
      distanceMeters: (json['distanceMeters'] as num?)?.toInt() ?? 0,
      durationSeconds: (json['durationSeconds'] as num?)?.toInt() ?? 0,
      steps: ((json['steps'] as List?) ?? [])
          .map((s) => CanonicalRouteStep.fromJson((s as Map).cast<String, dynamic>()))
          .toList(),
    );
  }

  Map<String, dynamic> toJson() => {
    'legIndex': legIndex,
    'distanceMeters': distanceMeters,
    'durationSeconds': durationSeconds,
    'steps': steps.map((s) => s.toJson()).toList(),
  };
}

/// Authoritative Route Information from the backend routing engine.
class RouteInfo {
  final int distanceMeters;
  final double distanceKm;
  final int durationSeconds;
  final int durationMin;
  final List<GeoPoint> coordinates;
  final Map<String, dynamic>? geometry;
  final List<CanonicalRouteLeg> legs;
  final List<CanonicalRouteStep> steps;
  final List<String> maneuvers;
  final bool avoidedMotorways;
  final String provider;

  const RouteInfo({
    required this.distanceMeters,
    required this.distanceKm,
    required this.durationSeconds,
    required this.durationMin,
    required this.coordinates,
    this.geometry,
    this.legs = const [],
    this.steps = const [],
    this.maneuvers = const [],
    this.avoidedMotorways = false,
    this.provider = 'authoritative',
  });

  factory RouteInfo.fromJson(Map<String, dynamic> json) {
    final distM = (json['distanceMeters'] as num?)?.toInt() ??
        (((json['distanceKm'] as num?)?.toDouble() ?? 0.0) * 1000).round();
    final distKm = (json['distanceKm'] as num?)?.toDouble() ?? (distM / 1000.0);
    final durSec = (json['durationSeconds'] as num?)?.toInt() ??
        (((json['durationMin'] as num?)?.toInt() ?? 0) * 60);
    final durMin = (json['durationMin'] as num?)?.toInt() ?? (durSec / 60).round();

    final coords = (json['coordinates'] as List? ?? [])
        .map((e) => GeoPoint.fromJson((e as Map).cast<String, dynamic>()))
        .toList();

    final legs = (json['legs'] as List? ?? [])
        .map((e) => CanonicalRouteLeg.fromJson((e as Map).cast<String, dynamic>()))
        .toList();

    final steps = (json['steps'] as List? ?? [])
        .map((e) => CanonicalRouteStep.fromJson((e as Map).cast<String, dynamic>()))
        .toList();

    final maneuvers = (json['maneuvers'] as List? ?? [])
        .map((e) => e.toString())
        .toList();

    return RouteInfo(
      distanceMeters: distM,
      distanceKm: distKm,
      durationSeconds: durSec,
      durationMin: durMin,
      coordinates: coords,
      geometry: json['geometry'] != null ? (json['geometry'] as Map).cast<String, dynamic>() : null,
      legs: legs,
      steps: steps,
      maneuvers: maneuvers,
      avoidedMotorways: json['avoidedMotorways'] == true,
      provider: json['provider']?.toString() ?? 'authoritative',
    );
  }

  Map<String, dynamic> toJson() => {
    'distanceMeters': distanceMeters,
    'distanceKm': distanceKm,
    'durationSeconds': durationSeconds,
    'durationMin': durationMin,
    'coordinates': coordinates.map((c) => c.toJson()).toList(),
    if (geometry != null) 'geometry': geometry,
    'legs': legs.map((l) => l.toJson()).toList(),
    'steps': steps.map((s) => s.toJson()).toList(),
    'maneuvers': maneuvers,
    'avoidedMotorways': avoidedMotorways,
    'provider': provider,
  };

  String get formattedDistance => TripPlan.formatDistance(distanceKm, distMeters: distanceMeters);
}

/// Authoritative Navigation Route contract containing all stops as waypoints.
class NavigationRoute {
  final GeoPoint origin;
  final GeoPoint destination;
  final List<GeoPoint> waypoints;
  final double distanceKm;
  final int distanceMeters;
  final int durationMin;
  final int durationSeconds;
  final List<GeoPoint> coordinates;
  final Map<String, dynamic>? geometry;

  const NavigationRoute({
    required this.origin,
    required this.destination,
    required this.waypoints,
    required this.distanceKm,
    required this.distanceMeters,
    required this.durationMin,
    required this.durationSeconds,
    required this.coordinates,
    this.geometry,
  });

  factory NavigationRoute.fromJson(Map<String, dynamic> json) {
    final distKm = (json['distanceKm'] as num?)?.toDouble() ?? 0.0;
    final distM = (json['distanceMeters'] as num?)?.toInt() ?? (distKm * 1000).round();
    final durMin = (json['durationMin'] as num?)?.toInt() ?? 0;
    final durSec = (json['durationSeconds'] as num?)?.toInt() ?? (durMin * 60);

    return NavigationRoute(
      origin: GeoPoint.fromJson((json['origin'] as Map).cast<String, dynamic>()),
      destination: GeoPoint.fromJson((json['destination'] as Map).cast<String, dynamic>()),
      waypoints: (json['waypoints'] as List? ?? [])
          .map((e) => GeoPoint.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      distanceKm: distKm,
      distanceMeters: distM,
      durationMin: durMin,
      durationSeconds: durSec,
      coordinates: (json['coordinates'] as List? ?? [])
          .map((e) => GeoPoint.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      geometry: json['geometry'] != null ? (json['geometry'] as Map).cast<String, dynamic>() : null,
    );
  }

  Map<String, dynamic> toJson() => {
    'origin': origin.toJson(),
    'destination': destination.toJson(),
    'waypoints': waypoints.map((w) => w.toJson()).toList(),
    'distanceKm': distanceKm,
    'distanceMeters': distanceMeters,
    'durationMin': durationMin,
    'durationSeconds': durationSeconds,
    'coordinates': coordinates.map((c) => c.toJson()).toList(),
    if (geometry != null) 'geometry': geometry,
  };
}

class TripPlan {
  final double distanceKm;
  final int distanceMeters;
  final int durationMin;
  final int durationSeconds;
  final List<GeoPoint> coordinates;

  /// True when expressways/motorways were excluded from this route because the
  /// vehicle (2-/3-wheeler) is legally barred from them.
  final bool avoidedMotorways;
  final int estimatedDays;
  final FuelPlan fuel;
  final FuelEstimate? fuelEstimate;
  final TollEstimate? toll;
  final RouteWeather? weather;
  final DepartureAdvice? departureAdvice;
  final List<RestBreak> restStops;
  final List<DayPlan> itinerary;
  final TripBudget? budget;
  final Map<String, List<PlaceOfInterest>> places;
  final List<WikiAttraction> wikiAttractions;
  final List<DestinationEvent> events;
  final List<GeoPoint> navigationWaypoints;
  final List<CanonicalRouteLeg> legs;
  final List<CanonicalRouteStep> steps;
  final List<String> maneuvers;
  final Map<String, dynamic>? geometry;
  final String? provider;
  final Vehicle? vehicleSnapshot;

  TripPlan({
    required this.distanceKm,
    int? distanceMeters,
    required this.durationMin,
    int? durationSeconds,
    required this.coordinates,
    this.avoidedMotorways = false,
    required this.estimatedDays,
    required this.fuel,
    this.fuelEstimate,
    required this.toll,
    required this.weather,
    required this.departureAdvice,
    required this.restStops,
    required this.itinerary,
    required this.budget,
    required this.places,
    this.wikiAttractions = const [],
    this.events = const [],
    this.navigationWaypoints = const [],
    this.legs = const [],
    this.steps = const [],
    this.maneuvers = const [],
    this.geometry,
    this.provider,
    this.vehicleSnapshot,
  })  : distanceMeters = distanceMeters ?? ((distanceKm * 1000).round()),
        durationSeconds = durationSeconds ?? (durationMin * 60);

  /// Centralized distance formatter across all platforms
  static String formatDistance(double distKm, {int? distMeters}) {
    final m = distMeters ?? (distKm * 1000).round();
    if (m < 1000) {
      return '$m m';
    } else {
      return '${(m / 1000.0).toStringAsFixed(1)} km';
    }
  }

  String get formattedDistance => formatDistance(distanceKm, distMeters: distanceMeters);

  factory TripPlan.fromJson(Map<String, dynamic> json) {
    final route = (json['route'] as Map).cast<String, dynamic>();
    final placesJson = ((json['places'] as Map?) ?? {}).cast<String, dynamic>();

    final distKm = (route['distanceKm'] as num).toDouble();
    final distMeters = (route['distanceMeters'] as num?)?.toInt() ?? (distKm * 1000).round();
    final durMin = (route['durationMin'] as num?)?.toInt() ?? 0;
    final durSec = (route['durationSeconds'] as num?)?.toInt() ?? (durMin * 60);

    return TripPlan(
      distanceKm: distKm,
      distanceMeters: distMeters,
      durationMin: durMin,
      durationSeconds: durSec,
      coordinates: (route['coordinates'] as List)
          .map((e) => GeoPoint.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      avoidedMotorways: (route['avoidedMotorways'] as bool?) ?? false,
      estimatedDays: json['estimatedDays'] as int,
      fuel: FuelPlan.fromJson((json['fuel'] as Map).cast<String, dynamic>()),
      fuelEstimate: json['fuelEstimate'] != null
          ? FuelEstimate.fromJson((json['fuelEstimate'] as Map).cast<String, dynamic>())
          : null,
      toll: json['toll'] != null ? TollEstimate.fromJson((json['toll'] as Map).cast<String, dynamic>()) : null,
      weather: json['weather'] != null ? RouteWeather.fromJson((json['weather'] as Map).cast<String, dynamic>()) : null,
      departureAdvice: json['departureAdvice'] != null
          ? DepartureAdvice.fromJson((json['departureAdvice'] as Map).cast<String, dynamic>())
          : null,
      restStops: (json['restStops'] as List? ?? [])
          .map((e) => RestBreak.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      itinerary: (json['itinerary'] as List? ?? [])
          .map((e) => DayPlan.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      budget: json['budget'] != null ? TripBudget.fromJson((json['budget'] as Map).cast<String, dynamic>()) : null,
      places: placesJson.map(
        (key, value) => MapEntry(
          key,
          (value as List).map((e) => PlaceOfInterest.fromJson((e as Map).cast<String, dynamic>())).toList(),
        ),
      ),
      wikiAttractions: (json['wikiAttractions'] as List? ?? [])
          .map((e) => WikiAttraction.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      events: (json['events'] as List? ?? [])
          .map((e) => DestinationEvent.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      navigationWaypoints: ((json['navigationWaypoints'] as List?) ?? [])
          .map((e) => GeoPoint.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      legs: ((route['legs'] as List?) ?? [])
          .map((e) => CanonicalRouteLeg.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      steps: ((route['steps'] as List?) ?? [])
          .map((e) => CanonicalRouteStep.fromJson((e as Map).cast<String, dynamic>()))
          .toList(),
      maneuvers: ((route['maneuvers'] as List?) ?? [])
          .map((e) => e.toString())
          .toList(),
      geometry: (route['geometry'] as Map?)?.cast<String, dynamic>(),
      provider: route['provider'] as String?,
      vehicleSnapshot: json['vehicleSnapshot'] != null
          ? Vehicle.fromJson((json['vehicleSnapshot'] as Map).cast<String, dynamic>())
          : null,
    );
  }

  TripPlan copyWith({
    double? distanceKm,
    int? distanceMeters,
    int? durationMin,
    int? durationSeconds,
    List<GeoPoint>? coordinates,
    bool? avoidedMotorways,
    int? estimatedDays,
    FuelPlan? fuel,
    FuelEstimate? fuelEstimate,
    TollEstimate? toll,
    RouteWeather? weather,
    DepartureAdvice? departureAdvice,
    List<RestBreak>? restStops,
    List<DayPlan>? itinerary,
    TripBudget? budget,
    Map<String, List<PlaceOfInterest>>? places,
    List<WikiAttraction>? wikiAttractions,
    List<DestinationEvent>? events,
    List<GeoPoint>? navigationWaypoints,
    List<CanonicalRouteLeg>? legs,
    List<CanonicalRouteStep>? steps,
    List<String>? maneuvers,
    Map<String, dynamic>? geometry,
    String? provider,
    Vehicle? vehicleSnapshot,
  }) {
    return TripPlan(
      distanceKm: distanceKm ?? this.distanceKm,
      distanceMeters: distanceMeters ?? this.distanceMeters,
      durationMin: durationMin ?? this.durationMin,
      durationSeconds: durationSeconds ?? this.durationSeconds,
      coordinates: coordinates ?? this.coordinates,
      avoidedMotorways: avoidedMotorways ?? this.avoidedMotorways,
      estimatedDays: estimatedDays ?? this.estimatedDays,
      fuel: fuel ?? this.fuel,
      fuelEstimate: fuelEstimate ?? this.fuelEstimate,
      toll: toll ?? this.toll,
      weather: weather ?? this.weather,
      departureAdvice: departureAdvice ?? this.departureAdvice,
      restStops: restStops ?? this.restStops,
      itinerary: itinerary ?? this.itinerary,
      budget: budget ?? this.budget,
      places: places ?? this.places,
      wikiAttractions: wikiAttractions ?? this.wikiAttractions,
      events: events ?? this.events,
      navigationWaypoints: navigationWaypoints ?? this.navigationWaypoints,
      legs: legs ?? this.legs,
      steps: steps ?? this.steps,
      maneuvers: maneuvers ?? this.maneuvers,
      geometry: geometry ?? this.geometry,
      provider: provider ?? this.provider,
      vehicleSnapshot: vehicleSnapshot ?? this.vehicleSnapshot,
    );
  }
}
