/**
 * Gemini AI Validation & Correction Layer for Itinerary Planning Engine
 *
 * Implements:
 * 1. Gemini AI as a Validation, Quality Control & Correction Feedback Layer
 * 2. Category as a HARD constraint using controlled taxonomy
 * 3. Deceptive place name rejection (e.g. "Temple View Restaurant" is not a temple)
 * 4. Multi-category distribution verification (Temples + Hills + Nature)
 * 5. Destination lock validation (e.g. Tirumala is never replaced by Tirupati or Chennai)
 * 6. Structured correction instructions output for the itinerary engine
 * 7. Fast deterministic local validator baseline + fallback
 */

const aiService = require("./aiService");
const { haversineDistanceKm } = require("../utils/geo");

// ── Controlled Category Taxonomy ─────────────────────────────────────────────

const CONTROLLED_CATEGORIES = Object.freeze([
  "temple",
  "hill",
  "nature",
  "waterfall",
  "beach",
  "historical",
  "fort",
  "museum",
  "wildlife",
  "adventure",
  "viewpoint",
  "spiritual",
  "cultural",
  "food",
  "shopping",
  "relaxation",
]);

// Category alias normalizer (maps user inputs like "Temples", "Scenic Hills", "Nature & Wildlife" to canonical keys)
function normalizeCategory(cat) {
  if (!cat) return "";
  const s = String(cat).toLowerCase().trim().replace(/[^a-z0-9]/g, "_");
  if (s.includes("temple") || s.includes("spiritual") || s.includes("devotion") || s.includes("pilgrim") || s.includes("pooja")) return "temple";
  if (s.includes("hill") || s.includes("mountain") || s.includes("ghat") || s.includes("peak")) return "hill";
  if (s.includes("waterfall") || s.includes("falls")) return "waterfall";
  if (s.includes("beach") || s.includes("coast") || s.includes("sea")) return "beach";
  if (s.includes("nature") || s.includes("forest") || s.includes("green") || s.includes("lake") || s.includes("valley")) return "nature";
  if (s.includes("wildlife") || s.includes("sanctuary") || s.includes("zoo") || s.includes("safari")) return "wildlife";
  if (s.includes("fort") || s.includes("palace")) return "fort";
  if (s.includes("museum") || s.includes("gallery") || s.includes("monument") || s.includes("heritage") || s.includes("history")) return "historical";
  if (s.includes("viewpoint") || s.includes("view") || s.includes("lookout") || s.includes("scenic")) return "viewpoint";
  if (s.includes("adventure") || s.includes("trek") || s.includes("rafting") || s.includes("camp")) return "adventure";
  if (s.includes("food") || s.includes("dining") || s.includes("restaurant") || s.includes("cuisine") || s.includes("tea") || s.includes("coffee")) return "food";
  if (s.includes("shop") || s.includes("mall") || s.includes("market") || s.includes("bazaar")) return "shopping";
  if (s.includes("relax") || s.includes("resort") || s.includes("spa") || s.includes("wellness")) return "relaxation";
  return s;
}

// Check if a place name deceptively pretends to be a category but is actually a restaurant/hotel/shop
function isDeceptivePlace(name, targetCategory) {
  if (!name) return false;
  const lower = name.toLowerCase();

  const commercialKeywords = [
    "restaurant", "hotel", "resort", "lodge", "dhaba", "cafe", "coffee",
    "bistro", "bakery", "bar", "pub", "shopping mall", "mall", "supermarket",
    "plaza", "hypermarket", "store", "jewellers", "textiles", "silks",
    "cinema", "theatre", "multiplex", "petrol", "fuel station"
  ];

  if (targetCategory === "temple" || targetCategory === "spiritual") {
    // If it has commercial food/hotel keywords and doesn't explicitly have temple/kovil/mandir in title
    for (const kw of commercialKeywords) {
      if (lower.includes(kw) && !lower.includes("temple trust") && !lower.includes("devasthanam")) {
        return true;
      }
    }
  }

  if (targetCategory === "hill" || targetCategory === "nature" || targetCategory === "viewpoint") {
    for (const kw of commercialKeywords) {
      if (lower.includes(kw)) return true;
    }
  }

  return false;
}

function clockMinutes(value) {
  if (!value) return null;
  const clean = String(value).trim();
  const match = /^(\d{1,2}):(\d{2})(?:\s*([ap]m))?$/i.exec(clean);
  if (!match) return null;
  let hours = Number(match[1]);
  const minutes = Number(match[2]);
  const ampm = match[3] ? match[3].toLowerCase() : null;

  if (ampm === "pm" && hours < 12) hours += 12;
  if (ampm === "am" && hours === 12) hours = 0;

  return hours >= 0 && hours < 24 && minutes >= 0 && minutes < 60
    ? hours * 60 + minutes
    : null;
}

// ── Gemini Validation System Prompt ──────────────────────────────────────────

const GEMINI_VALIDATOR_SYSTEM = `You are the lead travel planner and quality validator.
Your role is to INSPECT a proposed travel itinerary generated by an itinerary planning engine and either APPROVE it or REJECT it with precise correction instructions.

HARD RULES FOR EVALUATION:
1. DESTINATION INTEGRITY: The user's destination is a HARD CONSTRAINT. If the user asked for "Tirumala", the itinerary must reach and center on Tirumala. It must NOT substitute it with another city.
2. HARD CATEGORY CONSTRAINT: The categories selected by the user are HARD FILTERS, not suggestions.
   - If selected category = "temple", ALL activity stops must be real, verified temples/religious sites.
   - If selected category = "hill", activity stops must be hills, viewpoints, mountain spots.
   - Meal stops (breakfast, lunch, dinner) and rest stops are allowed as supporting logistics, but must NOT count as category attractions.
   - Deceptive names like "Temple View Restaurant" or "Hill Cafe" are NOT temples/hills. Reject them!
   - Unrelated places (shopping malls, water parks, random clubs) MUST be rejected unless user explicitly selected those categories.
3. MULTI-CATEGORY BALANCE: If the user selected multiple categories (e.g. Temples + Hills + Nature), there must be a balanced representation of all chosen categories across the trip days.
4. ROUTE RELEVANCE: Stops must lie strictly along the route corridor or within the destination area. Reject massive detours or unrelated distant cities.
5. REALISTIC TIMELINE: Days must not be overloaded or empty. Travel and visit times must be physically possible for the selected pace (Relaxed, Balanced, Packed).

You must respond ONLY with valid JSON matching this schema:
{
  "valid": true | false,
  "destinationValid": true | false,
  "categoryValid": true | false,
  "routeValid": true | false,
  "timeValid": true | false,
  "issues": [
    {
      "day": 1,
      "stop": "Place Name",
      "placeId": "place_id_if_known",
      "issue": "Specific explanation",
      "action": "REMOVE" | "REPLACE"
    }
  ],
  "missingCategories": ["category_name"],
  "requiredCorrections": [
    "Specific instruction for the itinerary engine to fix"
  ],
  "blacklistedPlaceIds": ["id1", "id2"],
  "blacklistedNames": ["name1", "name2"]
}`;

/**
 * Perform deterministic baseline validation first (fast, reliable guardrail).
 */
function deterministicValidate({
  itinerary,
  destination,
  origin,
  selectedCategories = [],
  durationDays = 1,
  mode = "balanced",
}) {
  const issues = [];
  const blacklistedPlaceIds = [];
  const blacklistedNames = [];
  const missingCategories = [];
  const requiredCorrections = [];
  let timeValid = true;
  const seenPlaces = new Set();

  const normDest = (destination?.name || destination || "").toLowerCase().trim();
  const days = itinerary.days || [];

  if (days.length === 0) {
    return {
      valid: false,
      destinationValid: false,
      categoryValid: false,
      routeValid: false,
      timeValid: false,
      issues: [{ day: 1, stop: "None", issue: "Itinerary has no days generated", action: "REPLACE" }],
      missingCategories: selectedCategories,
      requiredCorrections: ["Regenerate complete itinerary with daily timeline."],
      blacklistedPlaceIds: [],
      blacklistedNames: [],
    };
  }

  // 1. Destination Check
  let destinationValid = true;
  const destLower = normDest;
  const isTirumala = destLower.includes("tirumala");

  // Verify at least one day or block mentions or centers on destination
  let destinationReached = false;
  for (const d of days) {
    for (const b of (d.blocks || [])) {
      const bStr = `${b.title || ""} ${b.place || ""} ${b.address || ""} ${b.city || ""}`.toLowerCase();
      if (bStr.includes(destLower) || (isTirumala && (bStr.includes("tirumala") || bStr.includes("venkateswara")))) {
        destinationReached = true;
        break;
      }
    }
    if (destinationReached) break;
  }

  if (!destinationReached && normDest) {
    destinationValid = false;
    issues.push({
      day: 1,
      stop: "Destination Arrival",
      issue: `Itinerary does not visit the locked destination: ${destination?.name || destination}`,
      action: "REPLACE",
    });
    requiredCorrections.push(`Ensure itinerary explicitly anchors and visits ${destination?.name || destination}.`);
  }

  // 2. Category Check
  const normSelectedCats = selectedCategories.map(normalizeCategory).filter(Boolean);
  const selectedCatSet = new Set(normSelectedCats);
  const categoryCounts = new Map();
  normSelectedCats.forEach((c) => categoryCounts.set(c, 0));

  let categoryValid = true;

  // A stop is usable only when the engine grounded it to a real coordinate.
  // Names alone are not sufficient: they could have been hallucinated upstream.
  for (const d of days) {
    let previousEnd = null;
    let activityCount = 0;
    for (const b of (d.blocks || [])) {
      const start = clockMinutes(b.start);
      const end = clockMinutes(b.end);
      if (start == null || end == null || end < start || (previousEnd != null && start < previousEnd)) {
        timeValid = false;
        issues.push({
          day: d.day || 1,
          stop: b.place || b.title || "Timeline block",
          placeId: b.placeId,
          issue: "Timeline has missing, reversed, or overlapping time blocks",
          action: "REPLACE",
        });
      }
      if (end != null) previousEnd = Math.max(previousEnd ?? end, end);

      if (b.type !== "activity") continue;
      activityCount++;
      const name = String(b.place || b.title || "").trim();
      const hasCoordinates = Number.isFinite(Number(b.lat ?? b.latitude)) && Number.isFinite(Number(b.lng ?? b.longitude));
      if (!name || !hasCoordinates) {
        categoryValid = false;
        issues.push({
          day: d.day || 1,
          stop: name || "Unnamed stop",
          placeId: b.placeId,
          issue: "Activity is not a verified real location with a name and coordinates",
          action: "REPLACE",
        });
        if (b.placeId) blacklistedPlaceIds.push(b.placeId);
        if (name) blacklistedNames.push(name.toLowerCase());
      }

      const identity = String(b.placeId || name).toLowerCase().trim();
      if (identity && seenPlaces.has(identity)) {
        categoryValid = false;
        issues.push({ day: d.day || 1, stop: name, placeId: b.placeId, issue: "Duplicate activity location", action: "REMOVE" });
        if (b.placeId) blacklistedPlaceIds.push(b.placeId);
        if (name) blacklistedNames.push(name.toLowerCase());
      }
      seenPlaces.add(identity);
    }
    if (activityCount === 0 && selectedCategories.length > 0) {
      categoryValid = false;
      requiredCorrections.push(`Day ${d.day || 1} has no category activity. Add a verified stop matching the selected categories.`);
    }
  }

  if (selectedCatSet.size > 0) {
    for (const d of days) {
      for (const b of (d.blocks || [])) {
        if (b.type !== "activity") continue; // Meal and travel blocks are supporting stops

        const pName = b.place || b.title || "";
        const pCat = normalizeCategory(b.category || b.type || "");

        if (!CONTROLLED_CATEGORIES.includes(pCat)) {
          categoryValid = false;
          issues.push({
            day: d.day || 1,
            stop: pName,
            placeId: b.placeId,
            issue: `Stop has an unsupported category '${b.category || b.type || "unknown"}'`,
            action: "REPLACE",
          });
          if (b.placeId) blacklistedPlaceIds.push(b.placeId);
          if (pName) blacklistedNames.push(pName.toLowerCase().trim());
          continue;
        }

        // Deceptive Name Check
        for (const selectedCat of selectedCatSet) {
          if (isDeceptivePlace(pName, selectedCat)) {
            categoryValid = false;
            issues.push({
              day: d.day || 1,
              stop: pName,
              placeId: b.placeId,
              issue: `Deceptive place '${pName}' is a restaurant/commercial spot, not a genuine ${selectedCat}`,
              action: "REMOVE",
            });
            if (b.placeId) blacklistedPlaceIds.push(b.placeId);
            blacklistedNames.push(pName.toLowerCase().trim());
            break;
          }
        }

        // Generic Unrelated Attraction Check
        const lowerName = pName.toLowerCase();
        const isMall = lowerName.includes("mall") || lowerName.includes("shopping");
        const isWaterPark = lowerName.includes("water park") || lowerName.includes("amusement");

        if (isMall && !selectedCatSet.has("shopping")) {
          categoryValid = false;
          issues.push({
            day: d.day || 1,
            stop: pName,
            placeId: b.placeId,
            issue: `Shopping/Mall '${pName}' does not match selected categories: ${selectedCategories.join(", ")}`,
            action: "REMOVE",
          });
          if (b.placeId) blacklistedPlaceIds.push(b.placeId);
          blacklistedNames.push(pName.toLowerCase().trim());
          continue;
        }

        if (isWaterPark && !selectedCatSet.has("adventure")) {
          categoryValid = false;
          issues.push({
            day: d.day || 1,
            stop: pName,
            placeId: b.placeId,
            issue: `Water park '${pName}' does not match selected categories: ${selectedCategories.join(", ")}`,
            action: "REMOVE",
          });
          if (b.placeId) blacklistedPlaceIds.push(b.placeId);
          blacklistedNames.push(pName.toLowerCase().trim());
          continue;
        }

        // Count category match
        if (selectedCatSet.has(pCat)) {
          categoryCounts.set(pCat, (categoryCounts.get(pCat) || 0) + 1);
        } else {
          // If category is not selected, check if name matches any selected category keyword
          let nameMatchesSelected = false;
          for (const sCat of selectedCatSet) {
            if (sCat === "temple" && (lowerName.includes("temple") || lowerName.includes("kovil") || lowerName.includes("mandir") || lowerName.includes("devasthanam") || lowerName.includes("matha") || lowerName.includes("theertham"))) {
              categoryCounts.set("temple", (categoryCounts.get("temple") || 0) + 1);
              nameMatchesSelected = true;
              break;
            }
            if (sCat === "hill" && (lowerName.includes("hill") || lowerName.includes("viewpoint") || lowerName.includes("peak") || lowerName.includes("ghat") || lowerName.includes("shilathoranam"))) {
              categoryCounts.set("hill", (categoryCounts.get("hill") || 0) + 1);
              nameMatchesSelected = true;
              break;
            }
            if (sCat === "nature" && (lowerName.includes("park") || lowerName.includes("garden") || lowerName.includes("lake") || lowerName.includes("forest") || lowerName.includes("falls") || lowerName.includes("waterfall") || lowerName.includes("valley"))) {
              categoryCounts.set("nature", (categoryCounts.get("nature") || 0) + 1);
              nameMatchesSelected = true;
              break;
            }
          }

          if (!nameMatchesSelected && !b.isDestinationAnchor) {
            categoryValid = false;
            issues.push({
              day: d.day || 1,
              stop: pName,
              placeId: b.placeId,
              issue: `Place '${pName}' with category '${pCat}' does not match selected categories: ${selectedCategories.join(", ")}`,
              action: "REMOVE",
            });
            if (b.placeId) blacklistedPlaceIds.push(b.placeId);
            blacklistedNames.push(pName.toLowerCase().trim());
          }
        }
      }
    }

    // 3. Multi-Category Balance Check
    if (normSelectedCats.length > 1) {
      for (const [cat, count] of categoryCounts.entries()) {
        if (count === 0) {
          categoryValid = false;
          missingCategories.push(cat);
          requiredCorrections.push(`Itinerary has 0 stops for selected category '${cat}'. Add genuine ${cat} locations.`);
        }
      }
    }
  }

  // 4. Deterministic Destination Boundary & Forbidden City Validation
  let routeValid = true;
  const originName = (origin?.name || origin || "").toLowerCase();

  // Destination-specific forbidden city clusters
  let forbiddenCities = [];
  if (destLower.includes("tirumala") || destLower.includes("tirupati")) {
    forbiddenCities = ["chennai", "pondicherry", "mysore", "mysuru", "hyderabad", "madurai", "coimbatore", "kodaikanal", "ooty", "bengaluru", "bangalore"];
  } else if (destLower.includes("goa")) {
    forbiddenCities = ["bengaluru", "bangalore", "mumbai", "hyderabad", "chennai", "mysore", "mysuru", "delhi", "pune"];
  } else if (destLower.includes("ooty")) {
    forbiddenCities = ["chennai", "bengaluru", "bangalore", "mysore", "mysuru", "hyderabad", "mumbai", "goa"];
  }

  // Filter out the origin city so returning home/starting from origin isn't incorrectly flagged
  forbiddenCities = forbiddenCities.filter((city) => !originName.includes(city));

  for (const d of days) {
    for (const b of (d.blocks || [])) {
      // Don't flag start/return blocks when heading to/from origin
      if (b.type === "start" || b.type === "return") continue;

      const placeStr = `${b.title || ""} ${b.place || ""} ${b.address || ""} ${b.city || ""}`.toLowerCase();
      for (const kw of forbiddenCities) {
        if (placeStr.includes(kw)) {
          routeValid = false;
          issues.push({
            day: d.day || 1,
            stop: b.title || b.place,
            placeId: b.placeId,
            issue: `Unrelated distant city '${kw}' included on a trip to ${destination?.name || destination}`,
            action: "REMOVE",
          });
          if (b.placeId) blacklistedPlaceIds.push(b.placeId);
          blacklistedNames.push((b.place || b.title || "").toLowerCase().trim());
        }
      }

      // Coordinate-based distance validation if destination coordinate is known
      const destLat = destination?.lat ?? destination?.latitude;
      const destLng = destination?.lng ?? destination?.longitude;
      const bLat = b.lat ?? b.latitude;
      const bLng = b.lng ?? b.longitude;

      if (
        b.type === "activity" &&
        Number.isFinite(Number(destLat)) &&
        Number.isFinite(Number(destLng)) &&
        Number.isFinite(Number(bLat)) &&
        Number.isFinite(Number(bLng))
      ) {
        const distKm = haversineDistanceKm({ lat: destLat, lng: destLng }, { lat: bLat, lng: bLng });
        // Local destination activities must be within 75 km of the locked destination
        if (distKm > 75) {
          routeValid = false;
          issues.push({
            day: d.day || 1,
            stop: b.title || b.place,
            placeId: b.placeId,
            issue: `Activity '${b.title || b.place}' is ${Math.round(distKm)} km away, outside destination boundary (max 75 km)`,
            action: "REMOVE",
          });
          if (b.placeId) blacklistedPlaceIds.push(b.placeId);
          blacklistedNames.push((b.place || b.title || "").toLowerCase().trim());
        }
      }
    }
  }

  const valid = destinationValid && categoryValid && routeValid && timeValid && issues.length === 0;

  return {
    valid,
    destinationValid,
    categoryValid,
    routeValid,
    timeValid,
    issues,
    missingCategories,
    requiredCorrections,
    blacklistedPlaceIds: [...new Set(blacklistedPlaceIds)],
    blacklistedNames: [...new Set(blacklistedNames)],
  };
}

/**
 * Main Gemini Validator function.
 * Runs deterministic checks, then consults Gemini AI for deep qualitative validation.
 */
async function validateItineraryWithGemini({
  itinerary,
  destination,
  origin,
  selectedCategories = [],
  durationDays = 1,
  mode = "balanced",
  preferences = "",
}) {
  // Step 1: Run deterministic baseline validation
  const localCheck = deterministicValidate({
    itinerary,
    destination,
    origin,
    selectedCategories,
    durationDays,
    mode,
  });

  // If local check already found hard failures, return immediately with clear correction instructions
  if (!localCheck.valid) {
    console.warn(`[GEMINI VALIDATOR] Local check rejected itinerary: ${localCheck.issues.length} issue(s) detected.`);
    return localCheck;
  }

  // Step 2: Query Gemini AI for advanced semantic and travel quality validation
  const destName = destination?.name || destination || "Destination";
  const originName = origin?.name || origin || "Origin";

  // Build condensed summary of itinerary for Gemini to inspect
  const daySummaries = (itinerary.days || []).map((d) => ({
    day: d.day,
    title: d.title,
    theme: d.theme,
    totalDistanceKm: d.totalDistanceKm,
    activities: (d.blocks || [])
      .filter((b) => b.type === "activity" || b.isDestinationAnchor)
      .map((b) => ({
        place: b.place || b.title,
        placeId: b.placeId,
        category: b.category,
        time: `${b.start} - ${b.end}`,
        durationMinutes: b.durationMinutes,
      })),
    meals: (d.blocks || [])
      .filter((b) => b.type === "meal")
      .map((b) => `${b.title} (${b.start})`),
  }));

  const inspectionPrompt = `INSPECT THIS TRAVEL ITINERARY AGAINST USER CONSTRAINTS:

USER TRIP SPECIFICATIONS:
- Origin: "${originName}"
- Destination (LOCKED): "${destName}"
- Days: ${durationDays}
- Selected Categories (HARD FILTER): ${selectedCategories.length > 0 ? selectedCategories.join(", ") : "None specified"}
- Pace: "${mode}"
- User Preferences: "${preferences || "None"}"

PROPOSED ITINERARY FROM ENGINE:
${JSON.stringify(daySummaries, null, 2)}

INSPECTION CHECKLIST:
1. Is destination strictly preserved as "${destName}"? (Must not be replaced with a different city).
2. Are all activity stops genuine matches for the selected categories: ${selectedCategories.join(", ")}?
   - Reject malls, shopping areas, water parks unless requested.
   - Reject restaurants or hotels posing as temples or hills.
3. If multiple categories selected, are all of them represented?
4. Are all stops geographically logical along the corridor or at the destination?
5. Is the itinerary detailed, realistic, and adhering to the ${mode} pace?

Respond ONLY with the exact JSON schema requested.`;

  try {
    console.log("[GEMINI VALIDATOR] Calling Gemini AI to inspect itinerary quality...");
    const text = await aiService.generateWithRetry(inspectionPrompt, {
      system: GEMINI_VALIDATOR_SYSTEM,
      json: true,
      maxTokens: 4000,
    });

    if (text) {
      const geminiResult = JSON.parse(text);
      console.log(`[GEMINI VALIDATOR] Gemini inspection complete. Result valid: ${geminiResult.valid}`);

      // Merge local blacklist with Gemini's findings
      const mergedBlacklistIds = [
        ...new Set([
          ...(localCheck.blacklistedPlaceIds || []),
          ...(geminiResult.blacklistedPlaceIds || []),
          ...(Array.isArray(geminiResult.issues) ? geminiResult.issues.map((i) => i.placeId).filter(Boolean) : []),
        ]),
      ];

      const mergedBlacklistNames = [
        ...new Set([
          ...(localCheck.blacklistedNames || []),
          ...(geminiResult.blacklistedNames || []),
          ...(Array.isArray(geminiResult.issues) ? geminiResult.issues.map((i) => (i.stop || "").toLowerCase().trim()).filter(Boolean) : []),
        ]),
      ];

      const destinationValid = geminiResult.destinationValid !== false;
      const categoryValid = geminiResult.categoryValid !== false;
      const routeValid = geminiResult.routeValid !== false;
      const timeValid = geminiResult.timeValid !== false;
      const issues = Array.isArray(geminiResult.issues) ? geminiResult.issues : [];

      return {
        // Treat missing/contradictory flags as a rejection. A response cannot
        // approve an itinerary while reporting a failed hard constraint.
        valid: geminiResult.valid === true && destinationValid && categoryValid && routeValid && timeValid && issues.length === 0,
        destinationValid,
        categoryValid,
        routeValid,
        timeValid,
        issues,
        missingCategories: Array.isArray(geminiResult.missingCategories) ? geminiResult.missingCategories : [],
        requiredCorrections: Array.isArray(geminiResult.requiredCorrections) ? geminiResult.requiredCorrections : [],
        blacklistedPlaceIds: mergedBlacklistIds,
        blacklistedNames: mergedBlacklistNames,
      };
    }
  } catch (err) {
    console.warn("[GEMINI VALIDATOR] Gemini AI call failed, using deterministic verification result:", err.message);
  }

  // Fallback to local check if Gemini is unavailable
  return localCheck;
}

module.exports = {
  validateItineraryWithGemini,
  deterministicValidate,
  CONTROLLED_CATEGORIES,
  normalizeCategory,
  isDeceptivePlace,
};
