/**
 * Vehicle Data Provider Interface and CarDekho Implementation for VoyPlan.
 *
 * Provides a normalized vehicle catalog containing brands, models, variants,
 * and comprehensive vehicle specifications (fuelType, mileage, tankCapacity,
 * batteryCapacity, evRange, transmission, engine, seating, bodyType, price).
 */

class VehicleDataProvider {
  async getBrands() {
    throw new Error('getBrands() not implemented');
  }
  async getModels(brandId) {
    throw new Error('getModels() not implemented');
  }
  async getVariants(modelId) {
    throw new Error('getVariants() not implemented');
  }
  async getVehicleDetails(variantId) {
    throw new Error('getVehicleDetails() not implemented');
  }
  async searchVehicles(query, options = {}) {
    throw new Error('searchVehicles() not implemented');
  }
  async syncVehicles() {
    throw new Error('syncVehicles() not implemented');
  }
}

/**
 * CarDekho Normalized Vehicle Database Provider
 */
class CarDekhoVehicleProvider extends VehicleDataProvider {
  constructor() {
    super();
    this.source = 'CarDekho';
    this.dataVersion = '2026.3.1';
    this.lastSyncedAt = new Date().toISOString();
    this._initCatalog();
  }

  _initCatalog() {
    // Comprehensive normalized CarDekho vehicle catalog database
    this._brands = [
      { id: 'tata', name: 'Tata Motors', country: 'India', type: 'car', logo: 'tata' },
      { id: 'mahindra', name: 'Mahindra', country: 'India', type: 'car', logo: 'mahindra' },
      { id: 'toyota', name: 'Toyota', country: 'Japan', type: 'car', logo: 'toyota' },
      { id: 'hyundai', name: 'Hyundai', country: 'South Korea', type: 'car', logo: 'hyundai' },
      { id: 'maruti_suzuki', name: 'Maruti Suzuki', country: 'India', type: 'car', logo: 'maruti' },
      { id: 'kia', name: 'Kia', country: 'South Korea', type: 'car', logo: 'kia' },
      { id: 'honda', name: 'Honda', country: 'Japan', type: 'car', logo: 'honda' },
      { id: 'skoda', name: 'Skoda', country: 'Czech Republic', type: 'car', logo: 'skoda' },
      { id: 'volkswagen', name: 'Volkswagen', country: 'Germany', type: 'car', logo: 'volkswagen' },
      { id: 'mg', name: 'MG Motor', country: 'UK', type: 'car', logo: 'mg' },
      { id: 'nissan', name: 'Nissan', country: 'Japan', type: 'car', logo: 'nissan' },
      { id: 'renault', name: 'Renault', country: 'France', type: 'car', logo: 'renault' },
      { id: 'byd', name: 'BYD', country: 'China', type: 'car', logo: 'byd' },
      { id: 'bmw', name: 'BMW', country: 'Germany', type: 'car', logo: 'bmw' },
      { id: 'mercedes_benz', name: 'Mercedes-Benz', country: 'Germany', type: 'car', logo: 'mercedes' },
      { id: 'audi', name: 'Audi', country: 'Germany', type: 'car', logo: 'audi' },
      { id: 'volvo', name: 'Volvo', country: 'Sweden', type: 'car', logo: 'volvo' },
      { id: 'jeep', name: 'Jeep', country: 'USA', type: 'car', logo: 'jeep' },
      // 2-Wheelers
      { id: 'royal_enfield', name: 'Royal Enfield', country: 'India', type: 'motorcycle', logo: 're' },
      { id: 'hero', name: 'Hero MotoCorp', country: 'India', type: 'motorcycle', logo: 'hero' },
      { id: 'bajaj', name: 'Bajaj Auto', country: 'India', type: 'motorcycle', logo: 'bajaj' },
      { id: 'tvs', name: 'TVS Motor', country: 'India', type: 'motorcycle', logo: 'tvs' },
      { id: 'honda_2w', name: 'Honda 2-Wheelers', country: 'Japan', type: 'motorcycle', logo: 'honda' },
      { id: 'yamaha', name: 'Yamaha', country: 'Japan', type: 'motorcycle', logo: 'yamaha' },
      { id: 'suzuki_2w', name: 'Suzuki 2-Wheelers', country: 'Japan', type: 'motorcycle', logo: 'suzuki' },
      { id: 'ktm', name: 'KTM', country: 'Austria', type: 'motorcycle', logo: 'ktm' },
      { id: 'ola_electric', name: 'Ola Electric', country: 'India', type: 'motorcycle', logo: 'ola' },
      { id: 'ather', name: 'Ather Energy', country: 'India', type: 'motorcycle', logo: 'ather' },
    ];

    // Vehicles normalized catalog list
    this._vehicles = [
      // ── TATA MOTORS ────────────────────────────────────────────────────────
      {
        id: 'tata_nexon_petrol_mt',
        brandId: 'tata',
        brandName: 'Tata Motors',
        modelId: 'nexon',
        modelName: 'Nexon',
        variantId: 'creative_plus_petrol_mt',
        variantName: 'Creative Plus 1.2 Turbo Petrol MT',
        type: 'car',
        fuelType: 'petrol',
        mileage: 17.4,
        tankCapacity: 44.0,
        engine: '1199 cc Turbocharged',
        transmission: 'Manual 6-Speed',
        seatingCapacity: 5,
        bodyType: 'Compact SUV',
        priceRange: '₹8.15 - 15.60 Lakh',
        modelYear: 2026,
      },
      {
        id: 'tata_nexon_diesel_amt',
        brandId: 'tata',
        brandName: 'Tata Motors',
        modelId: 'nexon',
        modelName: 'Nexon',
        variantId: 'fearless_plus_diesel_amt',
        variantName: 'Fearless Plus 1.5 Kryotec Diesel AMT',
        type: 'car',
        fuelType: 'diesel',
        mileage: 23.2,
        tankCapacity: 44.0,
        engine: '1497 cc Turbo Diesel',
        transmission: 'AMT 6-Speed',
        seatingCapacity: 5,
        bodyType: 'Compact SUV',
        priceRange: '₹11.00 - 15.80 Lakh',
        modelYear: 2026,
      },
      {
        id: 'tata_nexon_ev_empowered',
        brandId: 'tata',
        brandName: 'Tata Motors',
        modelId: 'nexon_ev',
        modelName: 'Nexon.ev',
        variantId: 'empowered_plus_long_range',
        variantName: 'Empowered Plus 45 kWh Long Range',
        type: 'car',
        fuelType: 'ev',
        mileage: 0.0,
        tankCapacity: 0.0,
        batteryCapacityKwh: 45.0,
        evRangeKm: 465,
        engine: 'Permanent Magnet Synchronous Motor (143 bhp)',
        transmission: 'Single Speed Automatic',
        seatingCapacity: 5,
        bodyType: 'Compact SUV',
        priceRange: '₹14.49 - 19.49 Lakh',
        modelYear: 2026,
      },
      {
        id: 'tata_harrier_fearless_diesel',
        brandId: 'tata',
        brandName: 'Tata Motors',
        modelId: 'harrier',
        modelName: 'Harrier',
        variantId: 'fearless_plus_dark_at',
        variantName: 'Fearless Plus Dark Edition 2.0 Kryotec AT',
        type: 'car',
        fuelType: 'diesel',
        mileage: 14.6,
        tankCapacity: 50.0,
        engine: '1956 cc Kryotec Diesel',
        transmission: 'Automatic 6-Speed',
        seatingCapacity: 5,
        bodyType: 'Mid-size SUV',
        priceRange: '₹15.49 - 26.44 Lakh',
        modelYear: 2026,
      },
      {
        id: 'tata_safari_accomplished_diesel',
        brandId: 'tata',
        brandName: 'Tata Motors',
        modelId: 'safari',
        modelName: 'Safari',
        variantId: 'accomplished_plus_6s_at',
        variantName: 'Accomplished Plus 6-Seater 2.0 AT',
        type: 'car',
        fuelType: 'diesel',
        mileage: 14.5,
        tankCapacity: 50.0,
        engine: '1956 cc Kryotec Diesel',
        transmission: 'Automatic 6-Speed',
        seatingCapacity: 6,
        bodyType: 'Full-size SUV',
        priceRange: '₹16.19 - 27.34 Lakh',
        modelYear: 2026,
      },
      {
        id: 'tata_punch_icng',
        brandId: 'tata',
        brandName: 'Tata Motors',
        modelId: 'punch',
        modelName: 'Punch',
        variantId: 'accomplished_dazzle_icng',
        variantName: 'Accomplished Dazzle Twin-Cylinder iCNG',
        type: 'car',
        fuelType: 'cng',
        mileage: 26.99,
        tankCapacity: 60.0, // Twin 30L CNG tanks
        engine: '1199 cc Revotron Bi-Fuel',
        transmission: 'Manual 5-Speed',
        seatingCapacity: 5,
        bodyType: 'Micro SUV',
        priceRange: '₹6.13 - 10.20 Lakh',
        modelYear: 2026,
      },
      {
        id: 'tata_curvv_ev',
        brandId: 'tata',
        brandName: 'Tata Motors',
        modelId: 'curvv_ev',
        modelName: 'Curvv.ev',
        variantId: 'empowered_plus_55kwh',
        variantName: 'Empowered Plus A 55 kWh',
        type: 'car',
        fuelType: 'ev',
        mileage: 0.0,
        tankCapacity: 0.0,
        batteryCapacityKwh: 55.0,
        evRangeKm: 585,
        engine: 'PMSM 167 bhp Motor',
        transmission: 'Single Speed Automatic',
        seatingCapacity: 5,
        bodyType: 'SUV Coupe',
        priceRange: '₹17.49 - 21.99 Lakh',
        modelYear: 2026,
      },

      // ── MAHINDRA ──────────────────────────────────────────────────────────
      {
        id: 'mahindra_xuv700_ax7l_diesel_awd',
        brandId: 'mahindra',
        brandName: 'Mahindra',
        modelId: 'xuv700',
        modelName: 'XUV700',
        variantId: 'ax7_luxury_pack_diesel_awd',
        variantName: 'AX7 Luxury Pack 2.2 mHawk Diesel AWD AT',
        type: 'car',
        fuelType: 'diesel',
        mileage: 13.5,
        tankCapacity: 60.0,
        engine: '2198 cc mHawk Turbo Diesel (182 bhp)',
        transmission: 'Automatic 6-Speed (Torque Converter)',
        seatingCapacity: 7,
        bodyType: 'Mid-size SUV',
        priceRange: '₹13.99 - 26.99 Lakh',
        modelYear: 2026,
      },
      {
        id: 'mahindra_xuv700_ax7_petrol_at',
        brandId: 'mahindra',
        brandName: 'Mahindra',
        modelId: 'xuv700',
        modelName: 'XUV700',
        variantId: 'ax7_m_stallion_petrol_at',
        variantName: 'AX7 2.0 mStallion Turbo Petrol AT',
        type: 'car',
        fuelType: 'petrol',
        mileage: 12.0,
        tankCapacity: 60.0,
        engine: '1999 cc mStallion TGDi (197 bhp)',
        transmission: 'Automatic 6-Speed',
        seatingCapacity: 7,
        bodyType: 'Mid-size SUV',
        priceRange: '₹13.99 - 25.50 Lakh',
        modelYear: 2026,
      },
      {
        id: 'mahindra_scorpio_n_z8l_diesel_4x4',
        brandId: 'mahindra',
        brandName: 'Mahindra',
        modelId: 'scorpio_n',
        modelName: 'Scorpio-N',
        variantId: 'z8_luxury_diesel_4x4_at',
        variantName: 'Z8 L 2.2 Diesel 4X4 AT 7-Seater',
        type: 'car',
        fuelType: 'diesel',
        mileage: 13.8,
        tankCapacity: 57.0,
        engine: '2198 cc mHawk Diesel (172 bhp)',
        transmission: 'Automatic 6-Speed 4WD',
        seatingCapacity: 7,
        bodyType: 'Rugged SUV',
        priceRange: '₹13.60 - 24.54 Lakh',
        modelYear: 2026,
      },
      {
        id: 'mahindra_thar_roxx_diesel_4x4',
        brandId: 'mahindra',
        brandName: 'Mahindra',
        modelId: 'thar_roxx',
        modelName: 'Thar ROXX (5-Door)',
        variantId: 'ax7l_diesel_4x4_at',
        variantName: 'AX7L 2.2 mHawk Diesel 4x4 AT',
        type: 'car',
        fuelType: 'diesel',
        mileage: 13.2,
        tankCapacity: 57.0,
        engine: '2198 cc mHawk Diesel (172 bhp)',
        transmission: 'Automatic 6-Speed with Low Range',
        seatingCapacity: 5,
        bodyType: 'Off-Road SUV',
        priceRange: '₹12.99 - 22.49 Lakh',
        modelYear: 2026,
      },
      {
        id: 'mahindra_thar_3door_diesel',
        brandId: 'mahindra',
        brandName: 'Mahindra',
        modelId: 'thar',
        modelName: 'Thar 3-Door',
        variantId: 'lx_hard_top_diesel_4x4',
        variantName: 'LX Hard Top 2.2 Diesel 4x4 MT',
        type: 'car',
        fuelType: 'diesel',
        mileage: 13.0,
        tankCapacity: 57.0,
        engine: '2198 cc mHawk Diesel',
        transmission: 'Manual 6-Speed',
        seatingCapacity: 4,
        bodyType: 'Off-Road SUV',
        priceRange: '₹11.35 - 17.60 Lakh',
        modelYear: 2026,
      },
      {
        id: 'mahindra_bolero_neo_plus',
        brandId: 'mahindra',
        brandName: 'Mahindra',
        modelId: 'bolero_neo',
        modelName: 'Bolero Neo Plus',
        variantId: 'p10_9seater_diesel',
        variantName: 'P10 2.2 mHawk 9-Seater Diesel',
        type: 'car',
        fuelType: 'diesel',
        mileage: 14.8,
        tankCapacity: 60.0,
        engine: '2184 cc mHawk Diesel',
        transmission: 'Manual 6-Speed',
        seatingCapacity: 9,
        bodyType: 'MUV',
        priceRange: '₹11.39 - 12.49 Lakh',
        modelYear: 2026,
      },

      // ── TOYOTA ────────────────────────────────────────────────────────────
      {
        id: 'toyota_innova_crysta_zx_diesel',
        brandId: 'toyota',
        brandName: 'Toyota',
        modelId: 'innova_crysta',
        modelName: 'Innova Crysta',
        variantId: 'zx_7seater_diesel_mt',
        variantName: 'ZX 2.4 Diesel 7-Seater MT',
        type: 'car',
        fuelType: 'diesel',
        mileage: 12.5,
        tankCapacity: 55.0,
        engine: '2393 cc 2GD-FTV Diesel (148 bhp)',
        transmission: 'Manual 5-Speed',
        seatingCapacity: 7,
        bodyType: 'Premium MPV',
        priceRange: '₹19.99 - 26.30 Lakh',
        modelYear: 2026,
      },
      {
        id: 'toyota_innova_hycross_zx_hybrid',
        brandId: 'toyota',
        brandName: 'Toyota',
        modelId: 'innova_hycross',
        modelName: 'Innova Hycross',
        variantId: 'zx_o_strong_hybrid_ecvt',
        variantName: 'ZX(O) 2.0 Strong Hybrid e-CVT 7-Seater',
        type: 'car',
        fuelType: 'hybrid',
        mileage: 23.24,
        tankCapacity: 52.0,
        engine: '1987 cc 4-Cyl + Electric Motor (184 bhp combo)',
        transmission: 'e-CVT Automatic',
        seatingCapacity: 7,
        bodyType: 'Premium MPV',
        priceRange: '₹19.77 - 30.98 Lakh',
        modelYear: 2026,
      },
      {
        id: 'toyota_fortuner_gr_s_4x4_diesel',
        brandId: 'toyota',
        brandName: 'Toyota',
        modelId: 'fortuner',
        modelName: 'Fortuner',
        variantId: 'gr_s_2_8_diesel_4x4_at',
        variantName: 'GR-S 2.8 Diesel 4X4 AT (500 Nm)',
        type: 'car',
        fuelType: 'diesel',
        mileage: 11.2,
        tankCapacity: 80.0,
        engine: '2755 cc 1GD-FTV Diesel (201 bhp)',
        transmission: 'Automatic 6-Speed',
        seatingCapacity: 7,
        bodyType: 'Full-size SUV',
        priceRange: '₹33.43 - 51.44 Lakh',
        modelYear: 2026,
      },
      {
        id: 'toyota_urban_cruiser_hyryder_hybrid',
        brandId: 'toyota',
        brandName: 'Toyota',
        modelId: 'hyryder',
        modelName: 'Urban Cruiser Hyryder',
        variantId: 'v_hybrid_ecvt',
        variantName: 'V Strong Hybrid 1.5 e-CVT',
        type: 'car',
        fuelType: 'hybrid',
        mileage: 27.97,
        tankCapacity: 45.0,
        engine: '1490 cc Strong Hybrid',
        transmission: 'e-CVT Automatic',
        seatingCapacity: 5,
        bodyType: 'Mid-size SUV',
        priceRange: '₹11.14 - 20.19 Lakh',
        modelYear: 2026,
      },

      // ── HYUNDAI ───────────────────────────────────────────────────────────
      {
        id: 'hyundai_creta_sx_o_petrol_dct',
        brandId: 'hyundai',
        brandName: 'Hyundai',
        modelId: 'creta',
        modelName: 'Creta',
        variantId: 'sx_o_1_5_turbo_petrol_dct',
        variantName: 'SX(O) 1.5 Turbo Petrol DCT',
        type: 'car',
        fuelType: 'petrol',
        mileage: 18.4,
        tankCapacity: 50.0,
        engine: '1482 cc Turbo GDi Petrol (158 bhp)',
        transmission: '7-Speed Dual Clutch (DCT)',
        seatingCapacity: 5,
        bodyType: 'Mid-size SUV',
        priceRange: '₹11.00 - 20.15 Lakh',
        modelYear: 2026,
      },
      {
        id: 'hyundai_creta_sx_o_diesel_at',
        brandId: 'hyundai',
        brandName: 'Hyundai',
        modelId: 'creta',
        modelName: 'Creta',
        variantId: 'sx_o_1_5_crdi_diesel_at',
        variantName: 'SX(O) 1.5 CRDi Diesel Automatic',
        type: 'car',
        fuelType: 'diesel',
        mileage: 19.1,
        tankCapacity: 50.0,
        engine: '1493 cc U2 CRDi Diesel (114 bhp)',
        transmission: 'Automatic 6-Speed (Torque Converter)',
        seatingCapacity: 5,
        bodyType: 'Mid-size SUV',
        priceRange: '₹12.56 - 20.15 Lakh',
        modelYear: 2026,
      },
      {
        id: 'hyundai_i20_nline_n8_dct',
        brandId: 'hyundai',
        brandName: 'Hyundai',
        modelId: 'i20_n_line',
        modelName: 'i20 N Line',
        variantId: 'n8_1_0_turbo_dct',
        variantName: 'N8 1.0 Turbo GDi DCT',
        type: 'car',
        fuelType: 'petrol',
        mileage: 20.0,
        tankCapacity: 37.0,
        engine: '998 cc Turbo Petrol (118 bhp)',
        transmission: '7-Speed DCT',
        seatingCapacity: 5,
        bodyType: 'Hatchback',
        priceRange: '₹9.99 - 12.52 Lakh',
        modelYear: 2026,
      },
      {
        id: 'hyundai_ioniq5_ev',
        brandId: 'hyundai',
        brandName: 'Hyundai',
        modelId: 'ioniq_5',
        modelName: 'Ioniq 5',
        variantId: 'rwd_72_6kwh',
        variantName: 'Long Range RWD 72.6 kWh',
        type: 'car',
        fuelType: 'ev',
        mileage: 0.0,
        tankCapacity: 0.0,
        batteryCapacityKwh: 72.6,
        evRangeKm: 631,
        engine: 'Permanent Magnet Synchronous Motor (215 bhp)',
        transmission: 'Single Speed Automatic',
        seatingCapacity: 5,
        bodyType: 'Electric Crossover',
        priceRange: '₹46.05 Lakh',
        modelYear: 2026,
      },

      // ── MARUTI SUZUKI ─────────────────────────────────────────────────────
      {
        id: 'maruti_swift_zxi_plus_amt',
        brandId: 'maruti_suzuki',
        brandName: 'Maruti Suzuki',
        modelId: 'swift',
        modelName: 'Swift',
        variantId: 'zxi_plus_amt_dual_tone',
        variantName: 'ZXi Plus 1.2 Z-Series Petrol AMT',
        type: 'car',
        fuelType: 'petrol',
        mileage: 25.75,
        tankCapacity: 37.0,
        engine: '1197 cc 3-Cylinder Z12E Petrol',
        transmission: 'AMT 5-Speed',
        seatingCapacity: 5,
        bodyType: 'Hatchback',
        priceRange: '₹6.49 - 9.60 Lakh',
        modelYear: 2026,
      },
      {
        id: 'maruti_baleno_cng',
        brandId: 'maruti_suzuki',
        brandName: 'Maruti Suzuki',
        modelId: 'baleno',
        modelName: 'Baleno',
        variantId: 'zeta_s_cng_mt',
        variantName: 'Zeta S-CNG 1.2 DualJet MT',
        type: 'car',
        fuelType: 'cng',
        mileage: 30.61,
        tankCapacity: 55.0, // CNG cylinder water equivalent
        engine: '1197 cc DualJet Dual VVT',
        transmission: 'Manual 5-Speed',
        seatingCapacity: 5,
        bodyType: 'Premium Hatchback',
        priceRange: '₹6.66 - 9.88 Lakh',
        modelYear: 2026,
      },
      {
        id: 'maruti_grand_vitara_strong_hybrid',
        brandId: 'maruti_suzuki',
        brandName: 'Maruti Suzuki',
        modelId: 'grand_vitara',
        modelName: 'Grand Vitara',
        variantId: 'alpha_plus_strong_hybrid_cvt',
        variantName: 'Alpha+ Intelligent Electric Hybrid e-CVT',
        type: 'car',
        fuelType: 'hybrid',
        mileage: 27.97,
        tankCapacity: 45.0,
        engine: '1490 cc Full Hybrid Petrol (114 bhp total)',
        transmission: 'e-CVT Automatic',
        seatingCapacity: 5,
        bodyType: 'Mid-size SUV',
        priceRange: '₹10.87 - 20.09 Lakh',
        modelYear: 2026,
      },
      {
        id: 'maruti_ertiga_zxi_cng',
        brandId: 'maruti_suzuki',
        brandName: 'Maruti Suzuki',
        modelId: 'ertiga',
        modelName: 'Ertiga',
        variantId: 'zxi_s_cng_7s',
        variantName: 'ZXi 1.5 S-CNG 7-Seater MT',
        type: 'car',
        fuelType: 'cng',
        mileage: 26.11,
        tankCapacity: 60.0,
        engine: '1462 cc K15C Smart Hybrid CNG',
        transmission: 'Manual 5-Speed',
        seatingCapacity: 7,
        bodyType: 'MPV',
        priceRange: '₹8.69 - 13.03 Lakh',
        modelYear: 2026,
      },

      // ── KIA ───────────────────────────────────────────────────────────────
      {
        id: 'kia_seltos_gtx_plus_diesel_at',
        brandId: 'kia',
        brandName: 'Kia',
        modelId: 'seltos',
        modelName: 'Seltos',
        variantId: 'gtx_plus_1_5_diesel_at',
        variantName: 'GTX Plus 1.5 CRDi Diesel Automatic',
        type: 'car',
        fuelType: 'diesel',
        mileage: 19.1,
        tankCapacity: 50.0,
        engine: '1493 cc CRDi Diesel (114 bhp)',
        transmission: 'Automatic 6-Speed',
        seatingCapacity: 5,
        bodyType: 'Mid-size SUV',
        priceRange: '₹10.90 - 20.35 Lakh',
        modelYear: 2026,
      },
      {
        id: 'kia_ev6_gt_line_awd',
        brandId: 'kia',
        brandName: 'Kia',
        modelId: 'ev6',
        modelName: 'EV6',
        variantId: 'gt_line_awd_77_4kwh',
        variantName: 'GT-Line 77.4 kWh Dual Motor AWD',
        type: 'car',
        fuelType: 'ev',
        mileage: 0.0,
        tankCapacity: 0.0,
        batteryCapacityKwh: 77.4,
        evRangeKm: 708,
        engine: 'Dual Motor AWD (320 bhp, 605 Nm)',
        transmission: 'Single Speed Automatic',
        seatingCapacity: 5,
        bodyType: 'Electric Crossover',
        priceRange: '₹60.95 - 65.95 Lakh',
        modelYear: 2026,
      },

      // ── HONDA, SKODA, VOLKSWAGEN, MG ──────────────────────────────────────
      {
        id: 'honda_city_zx_ehev_hybrid',
        brandId: 'honda',
        brandName: 'Honda',
        modelId: 'city',
        modelName: 'City',
        variantId: 'zx_e_hev_strong_hybrid',
        variantName: 'ZX e:HEV Strong Hybrid e-CVT',
        type: 'car',
        fuelType: 'hybrid',
        mileage: 27.13,
        tankCapacity: 40.0,
        engine: '1498 cc Atkinson Cycle + Dual Motor (124 bhp)',
        transmission: 'e-CVT Automatic',
        seatingCapacity: 5,
        bodyType: 'Sedan',
        priceRange: '₹11.82 - 20.55 Lakh',
        modelYear: 2026,
      },
      {
        id: 'skoda_kushaq_monte_carlo_1_5_dsg',
        brandId: 'skoda',
        brandName: 'Skoda',
        modelId: 'kushaq',
        modelName: 'Kushaq',
        variantId: 'monte_carlo_1_5_tsi_dsg',
        variantName: 'Monte Carlo 1.5 TSI DSG (Active Cylinder Tech)',
        type: 'car',
        fuelType: 'petrol',
        mileage: 18.86,
        tankCapacity: 50.0,
        engine: '1498 cc TSI EVO Turbo Petrol (148 bhp)',
        transmission: '7-Speed Dual Clutch (DSG)',
        seatingCapacity: 5,
        bodyType: 'Compact SUV',
        priceRange: '₹10.89 - 18.79 Lakh',
        modelYear: 2026,
      },
      {
        id: 'vw_virtus_gt_plus_1_5_dsg',
        brandId: 'volkswagen',
        brandName: 'Volkswagen',
        modelId: 'virtus',
        modelName: 'Virtus',
        variantId: 'gt_plus_edge_1_5_tsi_dsg',
        variantName: 'GT Plus Edge 1.5 TSI DSG',
        type: 'car',
        fuelType: 'petrol',
        mileage: 19.62,
        tankCapacity: 45.0,
        engine: '1498 cc TSI Turbo Petrol (148 bhp)',
        transmission: '7-Speed DSG',
        seatingCapacity: 5,
        bodyType: 'Sedan',
        priceRange: '₹11.56 - 19.40 Lakh',
        modelYear: 2026,
      },
      {
        id: 'mg_windsor_ev_essence',
        brandId: 'mg',
        brandName: 'MG Motor',
        modelId: 'windsor_ev',
        modelName: 'Windsor EV',
        variantId: 'essence_38kwh',
        variantName: 'Essence 38 kWh Aero Lounge',
        type: 'car',
        fuelType: 'ev',
        mileage: 0.0,
        tankCapacity: 0.0,
        batteryCapacityKwh: 38.0,
        evRangeKm: 331,
        engine: 'Permanent Magnet Motor (134 bhp)',
        transmission: 'Single Speed Automatic',
        seatingCapacity: 5,
        bodyType: 'CUV',
        priceRange: '₹13.50 - 15.50 Lakh',
        modelYear: 2026,
      },
      {
        id: 'byd_seal_performance_awd',
        brandId: 'byd',
        brandName: 'BYD',
        modelId: 'seal',
        modelName: 'Seal',
        variantId: 'performance_awd_82_5kwh',
        variantName: 'Performance 82.56 kWh AWD (523 bhp)',
        type: 'car',
        fuelType: 'ev',
        mileage: 0.0,
        tankCapacity: 0.0,
        batteryCapacityKwh: 82.56,
        evRangeKm: 580,
        engine: 'Dual Motor AWD (523 bhp, 670 Nm, 0-100 in 3.8s)',
        transmission: 'Single Speed Automatic',
        seatingCapacity: 5,
        bodyType: 'Electric Sedan',
        priceRange: '₹41.00 - 53.00 Lakh',
        modelYear: 2026,
      },
      {
        id: 'bmw_3_series_gran_limousine_diesel',
        brandId: 'bmw',
        brandName: 'BMW',
        modelId: '3_series_gl',
        modelName: '3 Series Gran Limousine',
        variantId: '320ld_m_sport',
        variantName: '320Ld M Sport 2.0 TwinPower Turbo Diesel',
        type: 'car',
        fuelType: 'diesel',
        mileage: 19.6,
        tankCapacity: 59.0,
        engine: '1995 cc BMW TwinPower Turbo 4-Cyl (188 bhp)',
        transmission: 'Steptronic Sport 8-Speed Automatic',
        seatingCapacity: 5,
        bodyType: 'Luxury Sedan',
        priceRange: '₹60.60 - 62.00 Lakh',
        modelYear: 2026,
      },

      // ── MOTORCYCLES & SCOOTERS ─────────────────────────────────────────────
      {
        id: 'royal_enfield_himalayan_450',
        brandId: 'royal_enfield',
        brandName: 'Royal Enfield',
        modelId: 'himalayan',
        modelName: 'Himalayan 450',
        variantId: 'hanle_black_tubeless',
        variantName: 'Summit Hanle Black Tubeless Spoke Wheels',
        type: 'motorcycle',
        fuelType: 'petrol',
        mileage: 30.0,
        tankCapacity: 17.0,
        engine: '452 cc Sherpa Liquid-Cooled DOHC (40 bhp)',
        transmission: 'Manual 6-Speed with Assist Clutch',
        seatingCapacity: 2,
        bodyType: 'Adventure Tourer',
        priceRange: '₹2.85 - 2.98 Lakh',
        modelYear: 2026,
      },
      {
        id: 'royal_enfield_classic_350_reborn',
        brandId: 'royal_enfield',
        brandName: 'Royal Enfield',
        modelId: 'classic_350',
        modelName: 'Classic 350',
        variantId: 'stealth_black_dual_channel_abs',
        variantName: 'Stealth Black Dual-Channel ABS Alloy',
        type: 'motorcycle',
        fuelType: 'petrol',
        mileage: 37.0,
        tankCapacity: 13.0,
        engine: '349 cc J-Series Air-Oil Cooled (20.2 bhp)',
        transmission: 'Manual 5-Speed',
        seatingCapacity: 2,
        bodyType: 'Classic Cruiser',
        priceRange: '₹1.93 - 2.30 Lakh',
        modelYear: 2026,
      },
      {
        id: 'hero_splendor_plus_xtec',
        brandId: 'hero',
        brandName: 'Hero MotoCorp',
        modelId: 'splendor_plus',
        modelName: 'Splendor Plus',
        variantId: 'xtec_2_0_drum',
        variantName: 'XTEC 2.0 Digital Bluetooth Disc',
        type: 'motorcycle',
        fuelType: 'petrol',
        mileage: 65.0,
        tankCapacity: 9.8,
        engine: '97.2 cc Single Cylinder OHC (7.9 bhp)',
        transmission: 'Manual 4-Speed',
        seatingCapacity: 2,
        bodyType: 'Commuter',
        priceRange: '₹75,441 - 83,461',
        modelYear: 2026,
      },
      {
        id: 'tvs_apache_rtr_310',
        brandId: 'tvs',
        brandName: 'TVS Motor',
        modelId: 'apache_rtr_310',
        modelName: 'Apache RTR 310',
        variantId: 'bto_dynamic_pro_kit',
        variantName: 'BTO Dynamic Pro Kit with Bi-directional Quickshifter',
        type: 'motorcycle',
        fuelType: 'petrol',
        mileage: 30.0,
        tankCapacity: 11.0,
        engine: '312.12 cc Reverse-Inclined DOHC Liquid Cooled (35.6 bhp)',
        transmission: 'Manual 6-Speed with Slipper Clutch & Quickshifter',
        seatingCapacity: 2,
        bodyType: 'Naked Streetfighter',
        priceRange: '₹2.43 - 2.64 Lakh',
        modelYear: 2026,
      },
      {
        id: 'ola_s1_pro_gen2',
        brandId: 'ola_electric',
        brandName: 'Ola Electric',
        modelId: 's1_pro',
        modelName: 'S1 Pro Gen 2',
        variantId: 'gen2_4kwh',
        variantName: 'Gen 2 4 kWh 11 kW Mid-Drive Motor',
        type: 'motorcycle',
        fuelType: 'ev',
        mileage: 0.0,
        tankCapacity: 0.0,
        batteryCapacityKwh: 4.0,
        evRangeKm: 195,
        engine: '11 kW Peak Mid-Drive PMSM (120 km/h top speed)',
        transmission: 'Single Speed Automatic',
        seatingCapacity: 2,
        bodyType: 'Electric Scooter',
        priceRange: '₹1.34 Lakh',
        modelYear: 2026,
      },
      {
        id: 'ather_450_apex',
        brandId: 'ather',
        brandName: 'Ather Energy',
        modelId: '450_apex',
        modelName: '450 Apex',
        variantId: 'indium_blue_3_7kwh',
        variantName: 'Indium Blue 3.7 kWh with Warp+ Mode',
        type: 'motorcycle',
        fuelType: 'ev',
        mileage: 0.0,
        tankCapacity: 0.0,
        batteryCapacityKwh: 3.7,
        evRangeKm: 157,
        engine: '7.0 kW PMSM Motor (0-40 in 2.9s, Magic Twist Regen)',
        transmission: 'Belt Drive Automatic',
        seatingCapacity: 2,
        bodyType: 'Electric Scooter',
        priceRange: '₹1.89 Lakh',
        modelYear: 2026,
      },
    ];
  }

  async getBrands() {
    return this._brands;
  }

  async getModels(brandId) {
    if (!brandId) return [];
    const lower = brandId.toLowerCase();
    const modelsMap = new Map();
    for (const v of this._vehicles) {
      if (v.brandId.toLowerCase() === lower) {
        if (!modelsMap.has(v.modelId)) {
          modelsMap.set(v.modelId, {
            id: v.modelId,
            name: v.modelName,
            brandId: v.brandId,
            brandName: v.brandName,
            type: v.type,
            bodyType: v.bodyType,
            fuelTypes: new Set(),
            priceRange: v.priceRange,
          });
        }
        modelsMap.get(v.modelId).fuelTypes.add(v.fuelType);
      }
    }
    return Array.from(modelsMap.values()).map(m => ({
      ...m,
      fuelTypes: Array.from(m.fuelTypes),
    }));
  }

  async getVariants(modelId) {
    if (!modelId) return [];
    const lower = modelId.toLowerCase();
    return this._vehicles
      .filter(v => v.modelId.toLowerCase() === lower)
      .map(v => ({
        id: v.id,
        variantId: v.variantId,
        variantName: v.variantName,
        modelId: v.modelId,
        modelName: v.modelName,
        brandId: v.brandId,
        brandName: v.brandName,
        type: v.type,
        fuelType: v.fuelType,
        mileage: v.mileage,
        tankCapacity: v.tankCapacity,
        batteryCapacityKwh: v.batteryCapacityKwh || 0,
        evRangeKm: v.evRangeKm || 0,
        engine: v.engine,
        transmission: v.transmission,
        seatingCapacity: v.seatingCapacity,
        bodyType: v.bodyType,
        priceRange: v.priceRange,
        modelYear: v.modelYear,
        source: this.source,
        dataVersion: this.dataVersion,
      }));
  }

  async getVehicleDetails(vehicleId) {
    if (!vehicleId) return null;
    const v = this._vehicles.find(item => item.id === vehicleId);
    if (!v) return null;
    return {
      ...v,
      source: this.source,
      dataVersion: this.dataVersion,
      lastUpdated: this.lastSyncedAt,
    };
  }

  async searchVehicles(query, options = {}) {
    if (!query || query.trim().length === 0) {
      return this._vehicles.slice(0, options.limit || 20);
    }
    const q = query.toLowerCase().trim();
    const fuelFilter = options.fuelType ? options.fuelType.toLowerCase() : null;
    const typeFilter = options.type ? options.type.toLowerCase() : null;

    return this._vehicles.filter(v => {
      if (fuelFilter && v.fuelType !== fuelFilter) return false;
      if (typeFilter && v.type !== typeFilter) return false;

      const fullText = `${v.brandName} ${v.modelName} ${v.variantName} ${v.bodyType} ${v.fuelType}`.toLowerCase();
      return fullText.includes(q);
    }).slice(0, options.limit || 25);
  }

  async syncVehicles() {
    this.lastSyncedAt = new Date().toISOString();
    return {
      status: 'SUCCESS',
      source: this.source,
      dataVersion: this.dataVersion,
      totalBrands: this._brands.length,
      totalVehicles: this._vehicles.length,
      syncedAt: this.lastSyncedAt,
    };
  }
}

const vehicleDataProvider = new CarDekhoVehicleProvider();

module.exports = {
  VehicleDataProvider,
  CarDekhoVehicleProvider,
  vehicleDataProvider,
};
