import 'dart:convert';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../models/trip_extras.dart';
// Web download vs. non-web stub (same pattern as calendar_helper).
import 'calendar_export_stub.dart' if (dart.library.html) 'calendar_export_web.dart';

String _p2(int n) => n.toString().padLeft(2, '0');

String _icsEsc(String s) => s
    .replaceAll('\\', '\\\\')
    .replaceAll(',', '\\,')
    .replaceAll(';', '\\;')
    .replaceAll('\n', '\\n');

/// Exports the day-by-day plan as a PDF. On web this opens the browser's print
/// dialog (save as PDF); on mobile it opens the share/print sheet.
Future<void> exportPlanPdf(String tripName, List<PlanDay> days) async {
  final doc = pw.Document();
  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      build: (ctx) => [
        pw.Text(tripName, style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 4),
        pw.Text('Trip plan', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
        pw.Divider(),
        for (int di = 0; di < days.length; di++) ...[
          pw.SizedBox(height: 12),
          pw.Text('Day ${di + 1}: ${days[di].title}',
              style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold)),
          if (days[di].hotel.isNotEmpty)
            pw.Text('Stay: ${days[di].hotel}', style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700)),
          pw.SizedBox(height: 4),
          if (days[di].items.isEmpty)
            pw.Text('  (no items)', style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey))
          else
            for (int ii = 0; ii < days[di].items.length; ii++)
              pw.Bullet(
                text: '${ii + 1}. ${days[di].items[ii].text}'
                    '${days[di].items[ii].time.isNotEmpty ? '  (${days[di].items[ii].time})' : ''}',
                style: const pw.TextStyle(fontSize: 12),
              ),
        ],
        pw.SizedBox(height: 20),
        pw.Text('Generated by Voyplan', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey)),
      ],
    ),
  );
  await Printing.layoutPdf(onLayout: (format) async => doc.save(), name: '$tripName.pdf');
}

/// Exports the plan as an .ics calendar: one all-day event per day, sequential
/// from today. On web it downloads; on mobile it opens the share sheet.
Future<void> exportPlanIcs(String tripName, List<PlanDay> days) async {
  final now = DateTime.now();
  String stamp(DateTime d) {
    final u = d.toUtc();
    return '${u.year}${_p2(u.month)}${_p2(u.day)}T${_p2(u.hour)}${_p2(u.minute)}00Z';
  }

  final lines = <String>[
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Voyplan//Plan//EN',
    'CALSCALE:GREGORIAN',
  ];
  for (int di = 0; di < days.length; di++) {
    final date = DateTime(now.year, now.month, now.day).add(Duration(days: di));
    final dateStr = '${date.year}${_p2(date.month)}${_p2(date.day)}';
    final descParts = [
      ...days[di].items.map((e) => e.time.isNotEmpty ? '${e.time} ${e.text}' : e.text),
      if (days[di].hotel.isNotEmpty) 'Stay: ${days[di].hotel}',
    ];
    lines.addAll([
      'BEGIN:VEVENT',
      'UID:${date.millisecondsSinceEpoch}-$di@voyplan',
      'DTSTAMP:${stamp(now)}',
      'DTSTART;VALUE=DATE:$dateStr',
      'SUMMARY:${_icsEsc('Day ${di + 1}: ${days[di].title}')}',
      'DESCRIPTION:${_icsEsc(descParts.join('\n'))}',
      'END:VEVENT',
    ]);
  }
  lines.add('END:VCALENDAR');
  final ics = lines.join('\r\n');
  final filename = '${tripName.replaceAll(RegExp(r'[^A-Za-z0-9_-]'), '_')}.ics';

  if (kIsWeb) {
    downloadIcs(filename, ics);
  } else {
    await Share.shareXFiles([
      XFile.fromData(utf8.encode(ics), mimeType: 'text/calendar', name: filename),
    ], subject: tripName);
  }
}

/// A parsed place from an imported file.
class ImportedPlace {
  final String name;
  final double? lat;
  final double? lng;
  ImportedPlace(this.name, this.lat, this.lng);
}

/// Parses places from an imported file's text content. Supports GeoJSON
/// (.json/.geojson), GPX waypoints (.gpx), and plain text (one place per line).
List<ImportedPlace> parseImportedPlaces(String filename, String content) {
  final lower = filename.toLowerCase();
  final out = <ImportedPlace>[];
  try {
    if (lower.endsWith('.json') || lower.endsWith('.geojson') || content.trimLeft().startsWith('{')) {
      final data = jsonDecode(content);
      final features = (data is Map && data['features'] is List) ? data['features'] as List : const [];
      for (final f in features) {
        if (f is! Map) continue;
        final props = f['properties'] as Map?;
        final geom = f['geometry'] as Map?;
        final name = (props?['name'] ?? props?['title'] ?? 'Place').toString();
        double? lat, lng;
        if (geom != null && geom['type'] == 'Point' && geom['coordinates'] is List) {
          final c = geom['coordinates'] as List; // [lng, lat]
          lng = (c[0] as num?)?.toDouble();
          lat = (c[1] as num?)?.toDouble();
        }
        out.add(ImportedPlace(name, lat, lng));
      }
    } else if (lower.endsWith('.gpx') || content.contains('<wpt')) {
      // Simple GPX waypoint parse: <wpt lat="" lon="">...<name>..</name></wpt>
      final wpt = RegExp(r'<wpt[^>]*lat="([-\d.]+)"[^>]*lon="([-\d.]+)"[^>]*>(.*?)</wpt>', dotAll: true);
      final nameRe = RegExp(r'<name>(.*?)</name>', dotAll: true);
      for (final m in wpt.allMatches(content)) {
        final lat = double.tryParse(m.group(1) ?? '');
        final lng = double.tryParse(m.group(2) ?? '');
        final inner = m.group(3) ?? '';
        final name = nameRe.firstMatch(inner)?.group(1)?.trim() ?? 'Waypoint';
        out.add(ImportedPlace(name, lat, lng));
      }
    } else {
      for (final line in content.split(RegExp(r'[\r\n]+'))) {
        final t = line.trim();
        if (t.isNotEmpty) out.add(ImportedPlace(t, null, null));
      }
    }
  } catch (_) {
    // return whatever parsed successfully
  }
  return out;
}
